### ISSUE TITLE
Shadow option buttons must be on a ButtonColumn

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#101]
In some languages like Spanish the radio buttons do not fit because the messages are very long.

![screenshot_20170129_014709](https://cloud.githubusercontent.com/assets/7884292/22402442/fb17a866-e5c4-11e6-8556-0ae7015e2af8.png)

**Comment by psifidotos** [comment]
I dont agree in this !!!! 

Why dont you just translate for Spanish instead of,
"Only for locked applets" ,
You can translate just "lockeds applets" or
"locked elements"

The column solution creates the reverse problem **too much empty space** even at the default case which is english...

Please update this again

**Comment by audoban** [comment]
the problem is translate applets to Spanish, applets on spanish is "elemento gráfico" is a very long translation but is the standard translation used on all Plasma for the spanish language.

lockeds applets on Spanish "Elementos gráficos bloqueados"  + all applets + "Todos los gráficos bloqueados"
As you can see it is still very long, and it does not fit

**Comment by psifidotos** [comment]
how about to put it the header:

Shadows -> "Elementos Graficos Shadows"

and for the radio buttons just translate:
"none, locked, all"

**Comment by audoban** [comment]
In Spanish then.
"Ninguno, Bloqueados, Todos"
Is a better translation

**Comment by psifidotos** [comment]
agree, go for it...

**Comment by psifidotos** [comment]
@audoban will you update this to buttonrow?

**Comment by audoban** [comment]
ok.
