### ISSUE TITLE
Can I setup the same dock in two displays?

### ISSUE THREAD

**Issue by joaomaridalho** [psifidotos/Latte-Dock#1010]
Hi Love this launcher,

My only problem is I want to setup docks inevery display and keep them synced (pinned apps and oppened apps).

Thanks for your work,
João

**Comment by psifidotos** [comment]
> My only problem is I want to setup docks inevery display and keep them synced (pinned apps and oppened apps).

yep this is possible...

1. setup  your dock the way you like it
2. Tasks-> Launchers Group -> Global (this way you are goind to use the global launchers that are independent of docks and layouts and they are available everywhere)
3. Tasks-> Filters (I dont know if you would like to be filtered per screen or not)
4. after that dock is setup and ready, choose Copy Dock in order to copy it to other screens (this is going to be done automatically when you click Copy and multi-screens are active)

![default](https://user-images.githubusercontent.com/2216474/39098628-66fdf50e-4676-11e8-81ce-e1e0a22777d3.png)
