### ISSUE TITLE
Used memory info

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#111]
the used memory by Latte goes to also influence plasmashell?
it's just a curiosity?

plasmashell, as it is used, it will consume a lot of memory
and I had to create a tiny script to refresh it

the consumption of milk memory, is stable or it needs a system to flush the memory ?

**Comment by psifidotos** [comment]
> the used memory by Latte goes to also influence plasmashell?

the opposite, using Latte drops the memory usage of plasmashell a lot! in my system this went from 240mbyte to 110mbyte maximum. That is because all the memory used from plasma panels now it is used for Latte which is outside Plasma.

Aldo, breaking plasmashell your latte docks will still be there!!

> the consumption of milk memory, is stable or it needs a system to flush the memory ?

you can try and tell us :-), in the code i use frequently the qml garbage collector and when a dock is removed its resources are freed for the memory...

**Comment by JenaPlinsky** [comment]
mine, wants to be just a thought;) ... I have not been watching the data for the memory consumption .... I just noticed that when Latte starts, it is smooth and after an hour;) it is a bit less smooth ..... then I kill plasmashel and I will re launch, and everything returns to normal .... I just wondered, if the system could not completely discharged the memory ... I often notice a huge amount of virtual memory with no application running ... but I know that is not the case of Latte ;)
