### ISSUE TITLE
Latte icon appears pixelated for 64px.

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#122]
![dfg](https://cloud.githubusercontent.com/assets/2216474/22563518/8234c9ba-e989-11e6-9cc7-1a6476cb3689.png)

**Comment by psifidotos** [comment]
@audoban do you have why this is happening?

**Comment by audoban** [comment]
I have a suspicion but I need to confirm it.
this bug is related with #123

**Comment by audoban** [comment]
Okay, I think I already found the problem.

libtaskmanager pass to iconItem the icon as QIcon, but sometimes this icon don't have a name, only have some sizes availables then iconItem can't convert the icon to Plasma::Svg.

For this reason iconItem paint the launcher as a QIcon instead of Svg, and QIcon isn't scalable.

**Comment by audoban** [comment]
The solution is: Libtaskmanger should pass ever the QIcon with a name of icon.

**Comment by psifidotos** [comment]
must be duplicate for #123 

I confirmed this with regular taskmanager

@audoban or the libtaskmanager could just do its icon heuristics correctly... either way this is a libtaskmanager. Could you please report it to plasma developers? the libtaskmanager maintainer is very active so I think we will have a fast response how this to be fixed... thank u ...

**Comment by audoban** [comment]
Of course I will report it.

**Comment by psifidotos** [comment]
nice!! and upload the link to have a reference...
 
Thank u !!!!
