### ISSUE TITLE
Changing screen resolution makes latte crash

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/Latte-Dock#154]
Could you please try to confirm if this happens to you as well?

**Comment by psifidotos** [comment]
are you using master?

**Comment by kupiqu** [comment]
yes

**Comment by psifidotos** [comment]
Please follow this guidelines in order to provide us with a screenshot of the backtrace:

- Install ddd
- ddd latte-dock
- in ddd window write and execute, run
- when it crashes, click status from the menu, backtrace

This will show you a window with numbered lines, this could be helpful for us...

**Comment by kupiqu** [comment]
![image](https://cloud.githubusercontent.com/assets/3875196/22750645/9d2d5b72-edff-11e6-8df2-f1cc2bbc570e.png)

Hope it helps :)

**Comment by psifidotos** [comment]
ok... I can confirm this...
Thank you very much!!!!
It was also happening in my system...

strange thing is that the line producing the crash was the one that should prevent it... I uploaded the fix, in my system works ok now, changing screens geometry no crash happens...

**NOTICE FOR FUTURE IMPLEMENTATIONS**

the crash was created by the line:

```
if (!screen()) {
    return;
}
```

it is fixed by the following, but I dont know why, more investigation is needed...

```
if (!this->screen()) {
    return;
}

```

**Comment by kupiqu** [comment]
Great, it is working here now too!
