### ISSUE TITLE
Some geometry bug

### ISSUE THREAD

**Issue by divinae** [psifidotos/Latte-Dock#157]
There is some bug on my desktop when start Latte like u see on the screen. I can right-click this corner and open latte settings. I'm on Arch linux.
![screenshot_20170210_201026](https://cloud.githubusercontent.com/assets/15931906/22840364/84d6fff4-efcd-11e6-969a-45b64510757c.png)

**Comment by psifidotos** [comment]
Are you using latest master branch or version 0.5.91?

**Comment by psifidotos** [comment]
i am asking because it reminds me #75

**Comment by psifidotos** [comment]
Can you also upload your file 
.config/latte-dock-appletsrc

**Comment by divinae** [comment]
Actually I am using git version
(i have 2 config files?)


[lattedock-appletsrc](https://github.com/psifidotos/Latte-Dock/files/767623/lattedock-appletsrc.txt)
[Latte Dock-appletsrc](https://github.com/psifidotos/Latte-Dock/files/767622/Latte.Dock-appletsrc.txt)

**Comment by psifidotos** [comment]
- close latte
- remove both of them... (Latte Dock-appletsrc is very old, the git version now uses lattedock-appletsrc)
- restart latte
- if it works then try also a reboot your machine, this issue was related to autostart

if you are using latest master then this should be fixed, if it doesnt and happens again, upload again your new lattedock-appletsrc

**Comment by divinae** [comment]
New config fixed it.

**Comment by psifidotos** [comment]
nice :+1:
