### ISSUE TITLE
Small geometry issue with automatic icon shrink

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#182]
remain small geometry problem, it happens that entering and exiting always same point,  repeatedly itself shrink and then extend

**Comment by psifidotos** [comment]
I can not undertand what you are describing

**Comment by JenaPlinsky** [comment]
eheheh I Know ;)
with the same number of icons, the geometry dock appears still a little unstable
soon as I can, I make some screenshots

**Comment by JenaPlinsky** [comment]
Here it is
https://youtu.be/fRTz5X1KjTw

**Comment by psifidotos** [comment]
I can not understand.... what is the issue shown in the video?

**Comment by JenaPlinsky** [comment]
I think that the width of the dock should always remain the same

icon size change even if the number of icons is always the same

**Comment by psifidotos** [comment]
the automatic icon mechanism is already sophisticated and I am not planning to touch it in the near future...

the mechanism uses two different points from which shrinks and increases the icon size, at the same time it uses a prediction mechanism in order to evaluate the above points...

Latte from other docks makes a difference by providing elements that are not totally squared and some of them can animatte also... e.g. the systray that is orthogonal and the weather plasmoid that in vertical is not square and can be animated... 

at some point in the future we could look at this if it can be done any better but not a priority at this time...

**Comment by psifidotos** [comment]
@JenaPlinsky if I remember correctly you have the latest from repos...

do you use Qt 5.8? can you confirm #183 please?

**Comment by JenaPlinsky** [comment]
I realize the complexity of the algorithms !! 

here it is
@psifidotos  
![spectacle jt8143](https://cloud.githubusercontent.com/assets/24593950/23141725/7ab15fcc-f7b8-11e6-9fee-aa94b81f632f.png)

**Comment by psifidotos** [comment]
@JenaPlinsky can you confirm #183 ?

**Comment by JenaPlinsky** [comment]
I can not test,for now
unfortunately I still have mixed packets between leap and tumblewed
so, the context menu does not work ... I can not move to dodgeActive mode

**Comment by AndydeCleyre** [comment]
Here seems like as good a place as any to say I wish the icon size algorithm were a little greedier. My vertical dock usually seems to be sized a little smaller than it has to be, and it's too bad because it's the difference between the systray icons being in 1 vs 2 columns (I prefer 2 columns).

![image](https://cloud.githubusercontent.com/assets/1787385/26070796/e8566f52-3973-11e7-8946-89d0b0d4f1b3.png)

**Comment by psifidotos** [comment]
> My vertical dock usually seems to be sized a little smaller than it has to be, and it's too bad because it's the difference between the systray icons being in 1 vs 2 columns (I prefer 2 columns).

Latte has nothing to do with how plasma systray layouts its contents. Latte provides to systray exactly the same thickness with all the other widgets/plasmoids... searching the internet you can find many users complaining about it... for any requests concering systray you should forward them to bugs.kde.org

**Comment by AndydeCleyre** [comment]
I am totally aware of that situation, but that's not really what I'm saying.

1) When the vertical dock is wider, the systray will use two columns.

2) The vertical could and should be wider, as I have the preferred latte dock icon size maxed out, and there is unused space above and below the dock.

**Comment by psifidotos** [comment]
you mean that even though you have set a bigger icon size, Latte lowers it by itself?

**Comment by AndydeCleyre** [comment]
Yes. Not by much, but it could take a little more advantage of the space. And it happens that this little difference straddles an important threshold for systray, which makes this little difference very noticeable.

Here's another shot of it *almost* taking full advantage of the space, but not quite.

![spectacle tj6884](https://cloud.githubusercontent.com/assets/1787385/26071569/8df48e88-3976-11e7-94c5-84994a4d50cd.png)

**Comment by psifidotos** [comment]
one more time... are you refering to Latte's automatic icon size that shrinks the icon size when it is needed?

**Comment by AndydeCleyre** [comment]
Yes

**Comment by psifidotos** [comment]
1. Have you enabled Maximum Length: 100%

2. If you dont like the automatic shrinking you can disable it at: Tweaks -> Uncheck, Shrink applets size when it is needed

the algorithm considers also the zoom factor in order when the parabolic effect is active the applets to not exceed the maximum length of the dock

**Comment by AndydeCleyre** [comment]
1. Yes.

2. I can't disable automatic shrinking, because then if I open extra apps the dock doesn't fit on the screen and so is partially unusable.

3. Zoom is at 0%.

**Comment by psifidotos** [comment]
yeah ... good way to debug this then...
the mentioned case fall into this issue but I dont know when the situation will be improved...

the shrinking algorithm is complex enough...

**Comment by AndydeCleyre** [comment]
Can you point me to the code for that? I may try playing with it.

**Comment by psifidotos** [comment]
Of course...

containment/package/contents/ui/main.qml

line #1112, 
function updateAutomaticIconSize()

**Comment by AndydeCleyre** [comment]
@psifidotos I'm getting pretty good behavior here with the following adjustment:

https://github.com/psifidotos/Latte-Dock/compare/master...AndydeCleyre:feature/greedier-icon-sizing

In particular, I think it makes sense to use `zoomFactor-1` rather than `zoomFactor`. This makes key values `== 0` when zoom is not used, simplifying both grow and shrink limits to `== maxLength`.

That extra adjustment based on `iconMargin` is much more guess-y, but is going well so far.

**Comment by psifidotos** [comment]
no prob... I will give it a ride to see....

**Comment by psifidotos** [comment]
@AndydeCleyre very nice!! ;) I like it, and I merged it... ;)
