### ISSUE TITLE
The zoom effect looks like tremors.

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#195]
When the icons climb, it shows as if they are jumping or shaking
https://youtu.be/b3o6hfZ7POI

**Comment by psifidotos** [comment]
This is because of the algorithm used...

how did you support the zoom effect in candil?

**Comment by psifidotos** [comment]
I hadnt noticed how much it tremors....

**_The Zoom Algorithm internals:_**

1. by design its task has its own mousearea and at every time only 3 tasks maximum can be zoomed, the one having the mouse hovering and the two tasks next to it (left, right)...

2. when a task containsMouse is zoomed at maximum and triggers signals in order for the neighbour tasks to be zoomed accordingly. All the calculations are taken place only into the task that contains the mouse each time and these resulted zoom factors are sent to the neighbours through signals.

3. The variable which is used into the TaskDelegate for the zoom is called **mScale**

4. In order to not do calculations all the time the mScale is not updated in every mouse movement, currently there is a step of: **_(iconSize / 8)_**  e.g. icon size 64 px. gives a step of 8px. in order to update mScale

5. The mScale has a behavior in order for things to be done smoothly...

```
Behavior on mScale {
                NumberAnimation { duration: .... }
 }
```

6. the above mechanism is used also for the applets case...


I could try to disable **_(4)_** and provide different **_(5)_** but I cant think anything else...

trying to update the above could be a choice but this code is some much in the core of everything especially the (1) that a different approach wont be an easy task and trasition...

**Comment by psifidotos** [comment]
@audoban test branch **rendering** I disabled (4) and (5),

how does it behave in your system?

**Comment by psifidotos** [comment]
@audoban I tried to work on with the rendering branch but things break too fast... if you have any ideas, I am open...

**Comment by psifidotos** [comment]
@audoban please test the rendering brach.... the painting experience has been improved greatly!!! 

I am trying to synchronize correctly the signals to not break each other but it is promising...

**Comment by audoban** [comment]
> This is because of the algorithm used...

> how did you support the zoom effect in candil?

With the position relative of mouse vs factor of zoom. Using a parabolic equation.

```js
function scaleIcon(distance) {
    if (mouseEnter) {
        var scale = (-Math.pow(distance, 2)) / parent.max + dock.zoomFactor
        return Math.max(scale, 1.0)
    }
    return 1.0
}
```

this equation correspond to `scale(distance) = -distance^2 / max + zoomFactor`

the max is a constant between 0 and 1, the closer to zero the more open is the parabola.

the distance correspond to distance from of center of an icon to mouse position.

then the icon size is calculate with this binding.

```qml
property int iconSize: dock.visibility.state === Dock.Visible && mouseEnter
        ? TaskTools.scaleIcon(distance) * dock.iconSize : dock.iconSize
```

Is very tiny but very precise and smooth.

**Comment by audoban** [comment]
> @audoban test branch rendering I disabled (4) and (5),
how does it behave in your system?

> @audoban please test the rendering brach.... the painting experience has been improved greatly!!!
I am trying to synchronize correctly the signals to not break each other but it is promising...

I'm testing now.

**Comment by audoban** [comment]
I tried the rendering branch. But I can not feel the improvement, there is still that little tremor.

and the algorithm isn't precise. see how the icon of dolphin and telegram have a zoom factor > 1.0 but are very far.
This occur when you when you quickly move the cursor up and down.

![screenshot_20170221_144735](https://cloud.githubusercontent.com/assets/7884292/23181904/ba56a970-f844-11e6-9766-73a22e65ecec.png)

**Comment by psifidotos** [comment]
retest please

**Comment by audoban** [comment]
ok

**Comment by psifidotos** [comment]
@audoban, more algorithm internals:

the function doing the calculations is called calculatesScales inside the TaskDelegate... 

the algorithm is the following, lets assume that we have 3 tasks next to each other:
[1]-[2]-[3]

and the mouse enters [2]... then the calculate scales is called... based on the distance from the [2] center all three scales are calculated, for example if we have used 75% zoom factor,

[2], is always 1,75

[1]+[3] = always 2,75

in the center of [2],
[1] = 1,375
[2] = 1,75
[3] = 1,375

very near the edge of [2],
[1] = 1,75
[2] = 1,75
[3] = 1

every time the calculatescales is called is informing the rest tasks with signals to update their scaling. That way the calculations are made only once for each drawing circle
----------------
I just noticed that zoom factors are calculated in the code with precision of 2 decimal points... maybe this must be increased to 3 or 4....
-------

another point is that in the TaskDelegate there is a Flow inside a Flow.... I dont know if this could create the tremor. The first flow is used for the secret spacers that are used at the edges and the second flow to align correctly the task icon with the active/group indicator based on the dock's position, left, right, top, bottom
