### ISSUE TITLE
The popup help shows active/maximized windows as if they were minimized

### ISSUE THREAD

**Issue by JuanManuelM** [psifidotos/Latte-Dock#333]
Hi! Congratulations for your great work.
It seems that this issue occurs with some frequency since the latest versions...
![latte_screenshot1](https://cloud.githubusercontent.com/assets/25255465/24327946/a0a09434-11dd-11e7-8dfe-9b659cb1e1f0.png)
![latte_screenshot2](https://cloud.githubusercontent.com/assets/25255465/24327948/a2bc550a-11dd-11e7-8794-42149c38182d.png)

**Comment by psifidotos** [comment]
@audoban if you wanna check it... what happens is that for some reason the window thumbnails do not update correctly... I have restored the functionality that hides and shows the previews window almost instantly in order probably for kwin to update its buffers

**Comment by audoban** [comment]
@psifidotos leave me to fix this bug, I also discovered that latte uses many instances of tooltip, we have to be more careful with the memory, 1 instance for tooltip is sufficient.

Please leave me to fix this bug.

**Comment by psifidotos** [comment]
> @psifidotos leave me to fix this bug, I also discovered that latte uses many instances of tooltip, we have to be more careful with the memory, 1 instance for tooltip is sufficient.

@audoban you can try no prob but latte is using just one instance for tooltips, the window is called windowsPreviewDlg why do you think is using multiple ?

**Comment by audoban** [comment]
@psifidotos, the issue is relationated with the multiple creations of model for tootips groups

**Comment by psifidotos** [comment]
@audoban, you found a fix?

**Comment by audoban** [comment]
@psifidotos I'm reducing to the number of creations, I already achieved something but I think I can improve

**Comment by psifidotos** [comment]
@audoban sounds interesting... let's see...

**Comment by audoban** [comment]
@psifidotos I will upload the changes in the afternoon

**Comment by psifidotos** [comment]
@audoban did you manage to remove the timer and the previews are working ok ?

**Comment by audoban** [comment]
@psifidotos I'm avoid use timers for load the model into GridLayout

**Comment by psifidotos** [comment]
@audoban nice patch concerning the improvements with the memory but it doesnt solve the fundamental issues of previews.. If you wanna play you can try branch **nopreviewtimer** in which there is one commit disabling the workaround with the timer in order to achieve correct previews.

As a reference, the timer is used in order to hide the preview window and show it again in every task change. This is the only way I have found to show correct previews. If you wanna see the faulty behavior just try that branch and after showing previews for a task of 2 or more, move immediately into a task of one preview. In such case you will see that the preview shown is not the correct one...

example, a thunderbird that shows a dolphin preview instead...

![image](https://cloud.githubusercontent.com/assets/2216474/24360498/2229b566-1310-11e7-8873-f8220903a81c.png)

**Comment by audoban** [comment]
@psifidotos on my system I can't reproduce the bug. How ever leave me to try your patch for ensure the compatibility with plasma 5.8

**Comment by psifidotos** [comment]
The nopreviewtimer branch doesnt have any patch in it, it just disables a workaround in order to reproduce the issue in your system

**Comment by audoban** [comment]
@psifidotos ok I can reproduce the issue from branch nopreviewtimer, but the tooltips works fine from the master.

**Comment by psifidotos** [comment]
I just wanted you to able to reproduce the main issue with previews, issue 333 appeared when i tried to disable for a few commits in the past this workaround
