### ISSUE TITLE
Launch animation blocks launch for the entire animation duration

### ISSUE THREAD

**Issue by magnus-gross** [psifidotos/Latte-Dock#336]
I just updated Latte and I am no longer able to add launchers to latte dock by dragging and dropping them into the bar. I can drag and drop them in the actual latte applet, but this will cause them to be a launcher (the same when I right click when it is started and choose to always display the launcher), which means every time I want to launch it by clicking it, I have to wait for a 2 second or so launch animation to stop. So why don't you start the launch animation asynchronously to launching the actual app, instead of waiting for the animation to complete before launching? Alternatively reenable dragging and dropping apps into the latte bar, because right now I am unable to add launchers...

**Comment by magnus-gross** [comment]
OMG, I am stupid, there is an option for "Add launchers only in the corresponding area".
While this solves my initial problem, I still think you should reconsider the 2 second blocking launch animation. You can't just block the launch for 2 seconds, even for such nice animations...

**Comment by psifidotos** [comment]
> While this solves my initial problem, I still think you should reconsider the 2 second blocking launch animation. You can't just block the launch for 2 seconds, even for such nice animations..

why dont you set the Animations to None?

**Comment by psifidotos** [comment]
I just checked... the reason why the launch of the application is happening at the end, is because even though the user doesnt see it the launcher is removed and readded because of the behavior of plasma libtaskmanager, so the animation is not played to the end... I can trigger it just a bit earlier...

**Comment by magnus-gross** [comment]
I cannot confirm the fix. I do not set the animations to none, because I like the animations.
Wouldn't it be possible to launch the program and play the launch animation while the application is already started? Currently you have to wait the 2 seconds, it would be better to launch the application and then the animation. Or is this not possible?

**Comment by psifidotos** [comment]
> Wouldn't it be possible to launch the program and play the launch animation while the application is already started? 
> Currently you have to wait the 2 sconds, it would be better to launch the application and then the animation. Or is this not possible?

one more time... it is not possible because when the window is appearing the launcher is removed, so its animation breaks in the middle. This behavior is of plasma libtaskmanager and related to #72 for which we found a way to workaround the (72 issue) but unfortunately nothing can be done for what you are requesting... 

The last fix launches the app just a bit earlier and it is as early as can be in order for both the animation is played and the app launch correctly

**Comment by magnus-gross** [comment]
Ok, thanks for explaining :)
