### ISSUE TITLE
Clang compatiblity

### ISSUE THREAD

**Issue by Tids** [psifidotos/Latte-Dock#346]
Right now it seems you have to build it with GCC. When I build it via clang, it will build just fine, but you can not start the 

```
latte-dock
```

Often it will crash (segfault) then or the process just stucks. The desktop-applet on the other hand works, just the Dock (the "Panel"-View) not.

It would be nice if you could make it compatible with clang.

clang version 3.9.1
plasmashell 5.9.4
KDE Frameworks 5.32.0
Qt 5.8.0
Latte 0.6

**Comment by Petross404** [comment]
If you can, please provide a crash backtrace to begin with :)

**Comment by psifidotos** [comment]
There is no plan supporting clang... we havent discussed such a case...

I dont see what is the problem... cant you build Latte for your distro?

**Comment by Tids** [comment]
It's not that i can not build it. But it would require an exception in my auto-build system for an Arch/Manjaro repo. Also the KDE tries for best clang compatiblity, thats why i thought it would be the same for latte-dock.

I dont think this will help much, as usuall when there is something from arch, but here it is:
![image](https://cloud.githubusercontent.com/assets/18744080/24589557/b17e9cd8-17dc-11e7-8d7d-a58d5ad9c35a.png)

[Also attached the package build with clang.](https://github.com/psifidotos/Latte-Dock/files/888541/latte-dock-arch.zip)

Just extrackt and install via 

`pacman -U latte-dock-0.6.0-1-x86_64.pkg.tar.xz`

**Comment by psifidotos** [comment]
the packages provided from arch are not working correctly?

https://aur.archlinux.org/packages/latte-dock/
https://aur.archlinux.org/packages/latte-dock-git/

the crash is found inside the visibilitymanager.cpp so @audoban could give a glance...

@Tids personally I dont have any experience with clang... of course we accept patches as long as they dont break other things...

**Comment by Tids** [comment]
@psifidotos 

yes they work and the first one is what i use. But AUR gives just generic build instructions. The build process itself (makepkg) will use your local makepkg.conf for all your AUR packages. So, if you define clang as standard compiler in there - all your builds will use clang.

**Comment by Petross404** [comment]
I talked about it with some gentoo devs in irc (in order to prevent usage of clang when emerging latte) and they told me that most problably there is an undefined behavior somewhere.

Not sure what they meant, but again if you compiled the code with clang you might be able to see for yourselves what is the deal

**Comment by audoban** [comment]
@psifidotos the compatibility with clang can be possible. 

The crash appears in the creation of the VisibilityManagerPrivate(), I will try to experiment in the few days with clang, but we can't not promise anything.

**Comment by psifidotos** [comment]
@audoban this is not a priority...
it would be nice to be able supporting it but ok... one step at a time... :)

if there are any clang programmers out there that want to help, this is a very good opportunity!!! :)

**Comment by psifidotos** [comment]
@Tids can you please check for this with latest v0.6.2 ? we have fixed 4-5 crashes since v0.6.0 and this issue there is a big chance that was not related to clang...

**Comment by psifidotos** [comment]
@audoban  can I close this?

I have just built and installed our master with clang in openSUSE... no probs... what I think was happening is that @Tids fell into one of our initial crashes and this wasnt related at all with clang... it is the same happening when a plasmoid is crashing Latte but not plasmashell, the crash bug is there and should be fixed... and we probably fixed them (I mean the crashes that made the clang build to crash on startup)... ;)

Steps to build:

1. remove the build directory in order to not conflict with the g++ builds
2. export the following variables:
```
$ export CC=/usr/bin/clang
$ export CXX=/usr/bin/clang++
```
3. run `sh install.sh` 

all is working as expected... and there are even new warnings in our source code concerning,
- `... enumeration values not handled in switch` (this is not relevant and important)
- if statements that have bracked issues concerning the logical with && || (this will be fixed immediately)

**Comment by Tids** [comment]
Yep it now builds and runs just fine with clang 👍

Thank you!
