### ISSUE TITLE
System Load Applet is Cut Off

### ISSUE THREAD

**Issue by AndydeCleyre** [psifidotos/Latte-Dock#357]
`0.6.0`

![image](https://cloud.githubusercontent.com/assets/1787385/24630884/51c72318-188c-11e7-9bc8-1a89c6dc1f7d.png)

In the screenshot, you can see the system load applet near the bottom, just above the desktop pager, and it doesn't seem bound by the same size and position constraints as any of the other dock items.

**Comment by psifidotos** [comment]
> In the screenshot, you can see the system load applet near the bottom, just above the desktop pager, and it doesn't seem bound by the same size and position constraints as any of the other dock items.

- does this happen also with horizontal dock?
- how does it look with plasma vertical panel ?

**Comment by psifidotos** [comment]
it looks pretty ok in my system...

![image](https://cloud.githubusercontent.com/assets/2216474/24632804/42fea36e-18ce-11e7-98ed-5a58f9083e0d.png)

**Comment by AndydeCleyre** [comment]
I haven't been able to replicate the problem on a second machine. I'll see what I can find when I'm back at the problematic one.

**Comment by psifidotos** [comment]
plasma 5.8 maybe

**Comment by audoban** [comment]
@psifidotos @AndydeCleyre  It is surely the fault of the plasmoid, because it also happens with plasma panel.

**LatteDock**
![spectacle sc5677](https://cloud.githubusercontent.com/assets/7884292/24642324/3d876b0c-18cc-11e7-9537-cbde1fa4d3cc.png)

**plasmashell panel**
![spectacle fb5744](https://cloud.githubusercontent.com/assets/7884292/24642380/a73d5aca-18cc-11e7-8a16-63beab424746.png)

**Comment by AndydeCleyre** [comment]
Thanks for confirming @audoban
