### ISSUE TITLE
Request: Add option to disable Latte plasmoid

### ISSUE THREAD

**Issue by AdmcWolfy** [psifidotos/Latte-Dock#362]
There should be option to disable Latte plasmoid in latte dock, it can be implemented as ability to simply remove it like every other plasmoid or as checkbox in "tasks" tab.

**Comment by audoban** [comment]
actually, latte plasmoid can be removed from the contextual menu, what is the difference?

**Comment by psifidotos** [comment]
@audoban there are many users that do not want the Latte plasmoid at all and want to use Latte dock in other ways.... In my implementation I have prevented this in order to protect the user to not delete the last Latte plasmoid... All Latte plasmoids can be deleted as long as one remains active...

I dont know for the next release... I am still thinking how we should act .... Will we let the user to remove the last Latte plasmoid easily?

**Comment by psifidotos** [comment]
I will try to provide a Remove Latte plasmoid from Tweaks page next to add spacer... we will see how this goes...

**Comment by psifidotos** [comment]
![image](https://cloud.githubusercontent.com/assets/2216474/24901737/a56a14b0-1eb0-11e7-9244-fd9d0e633c85.png)
