### ISSUE TITLE
Request: please add keyboard shortcuts for windows unity / ms windows style

### ISSUE THREAD

**Issue by nicman23** [psifidotos/Latte-Dock#365]
It is a must for many people and a big usability enhancement

**Comment by psifidotos** [comment]
can you describe us please more the feature? are you refering to Alt+1, 2, ... enable, disable windows?

**Comment by nicman23** [comment]
basically the super key shortcuts present in now ms windows, unity and kde (and older in dockbarx)

To start, num is based on the order of the applications that are on the dock (including pinned and non rnning applications)

- `super + num` to launch an instance of the application if none is running or to cycle through the application group (optionally if only one application exists and is focused then the application is minimised)
- `shift + num` to launch a new instance
- `ctrl + num` to reverse cycle through the application group

**Comment by psifidotos** [comment]
all the previous behavior is supported from official  plasma taskmanager or only the first point?

**Comment by audoban** [comment]
@psifidotos this behavior should be implemented from libtaskmanager?

**Comment by psifidotos** [comment]
@audoban libtaskmanager plasma taskmanger already support the first point... this is why I asked for the second and third... I dint know that they were also supported... the (2) can be supported by us non concerning libtaskmanager and (3) also...

**Comment by psifidotos** [comment]
@audoban @nicman23 

some infos for the patch:
1. the patch is inside branch **_taskshortcuts_** because it probably breaks plasma 5.8 compatibility, so I dont want to merge it yet. The code is based 95% at plasma implementation
2. adds a new dependency for KGlobalAccel
3. the plasma implementation as of now supports only Meta+number to activate a task and no cycling through groups of windows or new instances

but with this patch the following is supported in Latte:
1. Meta+number: activates a task and for groups start cycling activation for the windows in the group (showing the present windows for groups just as plasma is doing can be easily implemented but i believe cycling windows is better)
2. Meta+Ctrl+number: create a new instance (Shift is not supported correctly from KGlobalAccel)
3. the user must activate the shortcuts from plasma systemsettings -> global shortcuts

**Comment by nicman23** [comment]
Thank you this is awesome, as you added it in the TODO, should we close this?

**Comment by psifidotos** [comment]
no... dont worry... it will be closed automatically when the patch is merged in the master branch... ;)

**Comment by nicman23** [comment]
btw, χίλια ευχαριστώ, δεν ξέρεις πόσο με έχεις βοηθήσει  :)
