### ISSUE TITLE
Blank apperance settings panel as desktop widget?

### ISSUE THREAD

**Issue by run27017** [psifidotos/Latte-Dock#397]
My os system is openSuse Leap 42.2 and KDE desktop. I add a desktop widget of Latte Plasmoid, and the apperance settings page is blank.

**Comment by psifidotos** [comment]
nice.... :) this has been reported from so many users so it would be nice to track this down...

@run27017 **_how did you install Latte ?_**

Hint1: the Latte plasmoid is just for demonstration purposes mainly but the the Appearance tab should show correctly of course... Latte Dock in order to run fully and provide all the features must be run by just executing the command: `latte-dock`

**Comment by psifidotos** [comment]
This must occur from false installation

**Comment by run27017** [comment]
@psifidotos I install latte-dock through the standard installing procedure from 'https://software.opensuse.org//download.html?project=home%3Aaudoban&package=latte-dock' one-click installation.

**Comment by psifidotos** [comment]
If you had tried a local install in the past this could be the reason...

Go to, widgets explorer, add widgets, installed, check if latte is appearing there... if it does uninstall that record
