### ISSUE TITLE
[Crash] - Latte-dock crash after select highlight windows on hovering

### ISSUE THREAD

**Issue by lafaurie** [psifidotos/Latte-Dock#412]
My system configuration is
KDE plasma 5.8.6
KDE frameworks 5.26.0
QT 5.6.1

When i select in task this option the dock closed unexpected

**Comment by psifidotos** [comment]
Is still crashing? What latte version are you using?

**Comment by lafaurie** [comment]
Im using 0.6.0

**Comment by psifidotos** [comment]
This is from #323 and you are right... the fix was introduced only for plasma 5.9 even though i just checked that can occur also with plasma 5.8 ,  i will upload a fix at the end of the week inside the v0.6 branch which is the one that will keep plasma 5.8 compatibility...

**Comment by lafaurie** [comment]
Thanks good work

**Comment by psifidotos** [comment]
@audoban this happened because plasma devs updated their private apis for TaskManagerBackend... they re-introduced a new variable called groupdialog from the plasma 5.9 repo inside the plasma 5.8.5 and greater. It is something Eike Hein had warned me about the use of private qml apis, these apis are not forced to keep compatibility

**Comment by audoban** [comment]
@psifidotos Ok the requirements will be updated.

**Comment by psifidotos** [comment]
@lafaurie  please test the fix inside the v0.6 branch
