### ISSUE TITLE
Config ui simplified

### ISSUE THREAD

**Issue by audoban** [psifidotos/Latte-Dock#47]
@psifidotos 
I've tried to simplify a bit the code of the configuration interface. But without changing the previous visual style.
Please try https://github.com/psifidotos/Latte-Dock/tree/config-ui-simplified2

**Comment by psifidotos** [comment]
Ok, there are many issues that must be fixed...
the following are by my system...

1. the config window is appearing in the middle of the dock (mid thickness), in the previous version this didnt happen, The config window was appearing exactly at the edge of the blue board.
2. the config contents go out of the window horizontally
3. the config window height is very low even though that my screen has a lot of vertical space... it might be a good idea that the height for the pages is based on the screen's height. It could be used the previous_height in cases that 40%(screen.height)>previous_used_height
4. I dont like the buttons on the bottom to take all the horizontal space, the Add and the Quit must be as minimum as possible, and the same goes for the remove button. I prefer each one to be 25% of the window width in every case. Too much attention.
5. I dont like the two rows for the visibility mode, I prefer the two columns instead because the buttons contain a lot of text in them
6. Clicking the spin boxes buttons, are highlighted both buttons, up and down, it 's better to behave independently
7. There should be a visual indicator when we are hovering a button of the spin button, either the up one or the down one, independently
8. the ms. text it should have a little opacity comparing to the numerical text in order to not take so much attention, italic would help also and a space between numerical and ms. text I think is also essential.
9. the spin boxes should be smaller in width, too much attention from their width, they could be 25% of the window width each one
10. in Tasks page the choices should have a left-margin... They must start more to the right and not be in the alignment with their headers

I suppose you prefer your spin boxes but they need for sure the above adjustments in order to feel relevant.

I still find my version visually more appealing, you can compare at the last screenshot...


![screen1](https://cloud.githubusercontent.com/assets/2216474/21754114/29725a94-d602-11e6-8fca-4622af8a8db5.png)
**_screen1_**

![screen3](https://cloud.githubusercontent.com/assets/2216474/21754117/3680c338-d602-11e6-9a6c-828474fb0b03.png)
**_screen3_**


![screenn](https://cloud.githubusercontent.com/assets/2216474/21754305/33d87a3c-d606-11e6-88f9-75d335a26d91.png)
**_current version_**

**Comment by psifidotos** [comment]
11. I observed in the code that the vertical scroll bar is always visible, I dont like it, the vertical scroll bar should be shown only if a page's contents are greater than the area's vsible window

@audoban can you upload some screenshots showing the problems you faced with the current config implementation in master? It could be easier and more apealing to just fix those

**Comment by audoban** [comment]
> 1. the config window is appearing in the middle of the dock (mid thickness), in the previous version this didnt happen, The config window was appearing exactly at the edge of the blue board.

This because the height is no longer static. But it's easy to fix

> 2. the config contents go out of the window horizontally

same with the current version. horizontal size is difficult to calculate.

![screenshot_20170108_182316](https://cloud.githubusercontent.com/assets/7884292/21754494/9dcb075c-d5cf-11e6-8d46-76b070685f69.png)
*version on Master.*

> 3. the config window height is very low even though that my screen has a lot of vertical space... it might be a good idea that the height for the pages is based on the screen's height. It could be used the previous_height in cases that 40%(screen.height)>previous_used_height

This depends on the language and plasma theme. This also happen with the version master. Height should be the sufficient as fit behavior tab. The height should not be static.

> 4. I dont like the buttons on the bottom to take all the horizontal space, the Add and the Quit must be as minimum as possible, and the same goes for the remove button. I prefer each one to be 25% of the window width in every case. Too much attention.

and I don't like the buttons of the version master xD, should not be 25%, because exist long strings. **must be as minimum as possible**

> 5. I dont like the two rows for the visibility mode, I prefer the two columns instead because the buttons contain a lot of text in them

do you prefer three rows, or a simple Flow item?

> 6. Clicking the spin boxes buttons, are highlighted both buttons, up and down, it 's better to behave independently
Two button above TextField is not the right way to do this, I propose that wait until QtQuick 2 be standard on Plasma5 for we can use this new [SpinBox](http://doc.qt.io/qt-5/qml-qtquick-controls2-spinbox.html)

![current SpinBox with Arc theme](https://cloud.githubusercontent.com/assets/7884292/21754782/740fa688-d5d5-11e6-9afc-357e8618b217.png)
*current SpinBox with Arc theme*

> 7. There should be a visual indicator when we are hovering a button of the spin button, either the up one or the down one, independently
> 8. the ms. text it should have a little opacity comparing to the numerical text in order to not take so much attention, italic would help also and a space between numerical and ms. text I think is also essential.

The current style of SpinBox with Plasma5 is really ugly, yes I agree with you.

> 9. the spin boxes should be smaller in width, too much attention from their width, they could be 25% of the window width each one

I don't know. I prefer centered spinbox, the width is responsibility the spinbox.

> 10. in Tasks page the choices should have a left-margin... They must start more to the right and not be in the alignment with their headers

yes, I'm agree.

> I suppose you prefer your spin boxes but they need for sure the above adjustments in order to feel relevant.

of course, the default spinbox style is very broken, I had to overwrite the current style a bit. But it's still ugly.

> I still find my version visually more appealing, you can compare at the last screenshot...

my version can be greatly improved, but I feel that my version have code more simple a maintainable, also I see visually they are almost the same.

**Comment by audoban** [comment]
> Two button above TextField is not the right way to do this, I propose that wait until QtQuick 2 be standard on Plasma5 for we can use this new SpinBox

Sorry Is not QtQuick 2 is **QtQuick.Controls 2**

**Comment by audoban** [comment]
I made improvements to most of the points you proposed.
https://github.com/psifidotos/Latte-Dock/tree/config-ui-simplified2

**Comment by psifidotos** [comment]
> I made improvements to most of the points you proposed.

ok, I will check it over to give feedback.

Answering some of the _previous points_:

> same with the current version. horizontal size is difficult to calculate.

I know, but we must do our best, horizontal scroll bar or contents width outside the window should be only the translators fault (_too long tranlations that is_). We could use the shadows row width from appearance page to set up the window width. I think it is the most text found in a row.

> Height should be the sufficient as fit behavior tab. The height should not be static.

just a column containing also the buttons at the bottom would had fixed that in previous version. The height souldnt be static but a consideration of the screen height in the calculations would help to not create too narrow or too long window. 

> and I don't like the buttons of the version master xD, should not be 25%, because exist long strings. must be as minimum as possible

this wasnt the behavior I observed, the buttons were taken up the entire window's width. Concerning long texts, translators are not given all the space they have in their minds. From ui translation teams a small standard tactic is to give 2*width based on the english text when short english texts are used. For example Quit button must have at least width of "QuitQuit" in order to handle translations, otherwise the translator should find a better shorter term.

Either way,  providing the minimum width needed based on the button's text is a better strategy and we could implement it.

> I don't know. I prefer centered spinbox

I dont have any objections to center them as long as this creates visual balance

> the width is responsibility the spinbox.

I dont like this. They take up too much space with no reason.

> do you prefer three rows, or a simple Flow item?

I 'd prefer Flow but it isnt that important as long as two columns layout is shown to the user.

> Sorry Is not QtQuick 2 is QtQuick.Controls 2

I have in my mind that the first version of Latte should be compatible with Plasma 5.8 . In general I think that in a month we could have a first release, there arent any major issues and after your fixes around placement land in master, I think we can take off.
For the second Latte version we could increase the requirement.

multi-screen support is not that important for a first release if we cant provide it. It could be a major feature for the next one and we could try wayland support in the third release.

If the above is accepted then I would propose to restore the previous spin boxes for the first release and make them a little nicer for other themes, just putting the buttons in verticalCenter could be an easy fix. If in second release we have a better spin box, no objections from me.

I dont have any objections to keep your codepage for the configuration window but from design point of view we need something more robust...

**_We_** must make it look nice in both of our computers :)

**Comment by psifidotos** [comment]
better with the scrollbars but still ugly...

![screenn2](https://cloud.githubusercontent.com/assets/2216474/21765960/72f7472a-d674-11e6-9584-44ca57aa7b40.png)


I will create based on your edition what I consider a better experience and I will upload it in a different branch for review

**Comment by psifidotos** [comment]
please test config2 branch and send me screenshots to see any problems in your system....

latest arc theme in my system from config2 branch:

![arcn1](https://cloud.githubusercontent.com/assets/2216474/21768547/d2427958-d682-11e6-9b36-c02c09211da3.png)

**Comment by audoban** [comment]
Much better. 👍 

But spinbox still ugly.

![screenshot_20170109_125155](https://cloud.githubusercontent.com/assets/7884292/21776836/75d72ac8-d66a-11e6-8e64-1cd669846562.png)
*branch config 2*

I do somes modification to lattespinbox on the branch https://github.com/psifidotos/Latte-Dock/tree/improve-spinbox

![screenshot_20170109_124227](https://cloud.githubusercontent.com/assets/7884292/21776895/b2717948-d66a-11e6-89ec-e8d76df5e105.png)

![screenshot_20170109_125620](https://cloud.githubusercontent.com/assets/7884292/21777023/1599fa7c-d66b-11e6-9e48-e275fc278cb2.png)
*improve-spinbox*

**Comment by audoban** [comment]
I was rebase config-ui-simplified2. All last commits of spinbox branch and config2 are on config-ui-simplified2

**Comment by psifidotos** [comment]
Nice !!! I like it too! 

I had a small issue with LatteTextField becoming too big and the contents of Behavior Page were going too near the window edge...

I lowered a bit the metrics for LatteTextField, can you test branch **config4** please?

**Comment by audoban** [comment]
ok, will try

**Comment by audoban** [comment]
looks very good, but I found a overflow of int value on the class LatteTextField. This happens when the user delete all text with the cursor. But It was fixed, my branch, config-ui-simplified2.

Also add a auto increment or decrement when the user hold press the buttons + and -

**Comment by psifidotos** [comment]
> looks very good, but I found a overflow of int value on the class LatteTextField. This happens when the user delete all text with the cursor. But It was fixed, my branch, config-ui-simplified2.

> Also add a auto increment or decrement when the user hold press the buttons + and -

Very nice!!! I checked it and it's fine!!!

Ship it in master!!!

**Comment by audoban** [comment]
then I will push all commits to master. 👍

**Comment by psifidotos** [comment]
nice!!!

I have found a small solution for configuration window placement on startup. The fix is in branch **config** I changed the main ColumnLayout to Column and made some small margins adjustments afterwards... Can you check it over please? In my system this fixes almost all problems with window placement, probably accelerates the calculations for the window's height

**Comment by psifidotos** [comment]
merged and fixed....
