### ISSUE TITLE
System Tray/Notifications widget is unable to show notifications

### ISSUE THREAD

**Issue by slagiewka** [psifidotos/Latte-Dock#487]
I've just decided to go ahead and replace all my panels with Latte as I think it's superior to regular panels in most configuration related matters.

One thing I've noticed almost immediately - notifciations from the System Tray or standalone Notifications widgets are not shown on my desktop. For now I've replaced two panels with Latte and have one panel left over. Neither of Latte panels shows notifciations, the regular panel still works as expected.

Is there any configuration that I've missed and would allow me to see my notifications again? Or is it intended and switching panels to Latte is a no-go?

**Comment by psifidotos** [comment]
@slagiewka it should work just fine at least in my system it does...

1. Have you added a systray in one of the latte docks? and have you enabled the notifications in it?

2. does the 3rd plasma panel containining a notifications applet or systray?

3. you could try to remove the 3rd plasma panel and restart latte in order to register itself properly

you can always execute in command line: `notify-send "hello..."` in order to test where the notifications are shown

**Comment by psifidotos** [comment]
this is from my system

![image](https://cloud.githubusercontent.com/assets/2216474/26450798/da825d32-4161-11e7-8360-71d576720f12.png)

**Comment by slagiewka** [comment]
Of course I am testing with notify-send. I've removed the tray in the regular pane and surprisingly the two trays in Latte started showing notifications.

I will do more testing and get back to you if anything is still wrong.

**Comment by psifidotos** [comment]
nice...
