### ISSUE TITLE
Plasma 5.10 Mutimedia Keys fix might affect you

### ISSUE THREAD

**Issue by Zren** [psifidotos/Latte-Dock#519]
https://phabricator.kde.org/D6095

I'm not certain what your process's `qApp->applicationName()` value is, so you might want to tell them to use ` || appName == '...'` for the short term fix if they use it.

**Comment by psifidotos** [comment]
our  `qApp->applicationName()` is latte-dock, by this fix the multimedia keys wont work for Latte but this is better because afterwards we can propose our solution and fix also https://github.com/psifidotos/Latte-Dock/issues/402

currently, when a Latte dock and a plasma panel exists the media action is sent twice because the mpris engine activates for both of them the shortcuts

**Comment by psifidotos** [comment]
we can move this discussion at #402
