### ISSUE TITLE
Trash not supported

### ISSUE THREAD

**Issue by wandi34** [psifidotos/Latte-Dock#524]
I tried to move the trash folder of my desktop to the dock. Worked fine, the icon was shown in the dock.

But now I have the following problems:

- I cannot move files to the trash in the dock, so they get deleted (like in OSX)

- It is not possible to remove the trash icon from the dock. Only way I found is to delete the dock and start from a new config without the trash

This bug is not too important but may be confusing for new people.

**Comment by psifidotos** [comment]
These are not bugs, you just need help in order to figure out how to achieve them...

> I cannot move files to the trash in the dock, so they get deleted (like in OSX)

you can add the Trash applet with two ways:
1. from the Widgets Explored drag the Trash applet directly onto the dock
2. drag the Trash directory onto the dock and from the pop up menu that is appearing choose the Trash applet, not the folder!

both of them are the plasma way to achieve this and nothing related to Latte...

> It is not possible to remove the trash icon from the dock. Only way I found is to delete the dock and start from a new config without the trash

of course you can delete it and any other applet that you will add in the dock. Removing applets in permitted only in editing mode in order to protect the user from accidentaly deleting them. The Latte editing mode is when the Latte configuration window is shown (this is also one more reason why we draw a blueprint behind the dock in such case). In editing mode you can delete applets (from their tooltips or from right-clicking them) and of course you can move them around...

I hope that helps...
