### ISSUE TITLE
Latte crashed on Primary disaplay change

### ISSUE THREAD

**Issue by pecigonzalo** [psifidotos/Latte-Dock#538]
As explained in the title, I have 2 screens and i noticed some seg faults when changing primary display or connecting the secondary.

```
[debug 18:23:43.7171] -   Delayer  
[debug 18:23:43.7272] -       D, found screen:  "eDP1"
[debug 18:23:43.7272] -       D, found screen:  "DP1-1"
[debug 18:23:43.7272] - dock screen exists  :::  true
[debug 18:23:43.7272] - adapting to screen...
[debug 18:23:43.7878] -   Delayer  
[debug 18:23:43.7878] -       D, found screen:  "eDP1"
[debug 18:23:43.7878] -       D, found screen:  "DP1-1"
[debug 18:23:43.7878] - dock screen exists  :::  true
[debug 18:23:43.7878] - adapting to screen...
[1]    28068 segmentation fault (core dumped)  latte-dock -r -d

```

**Comment by psifidotos** [comment]
Are you using master branch?

**Comment by psifidotos** [comment]
follow #147 to produce a backtrace image

**Comment by slagiewka** [comment]
Although I do not mark any of my displays as primary, I do observe Latte crashing from time to time when displays change. Unfortunately, I could not make it crash when ran with ddd, but I'll keep trying, believe me ;)

**Comment by pecigonzalo** [comment]
@psifidotos Thanks, ill provide the logs ASAP

**Comment by pecigonzalo** [comment]
Changing virtual desktops:
![image](https://user-images.githubusercontent.com/9908105/27217777-9b0356fe-527b-11e7-8508-1c91b71e124c.png)

Changin primary:
![image](https://user-images.githubusercontent.com/9908105/27217858-eaca87ca-527b-11e7-820c-f716fbda4297.png)

**Comment by psifidotos** [comment]
have you installed Latte from master yourself?

**Comment by pecigonzalo** [comment]
From AUR

**Comment by psifidotos** [comment]
These backtraces they look more as crashes from an applet and not from Latte related code...

suspicious applets could be, Pager, Active Window Control, User Switcher, etc...

Normally you should also install the debug package for Latte if AUR provides that in order to be certain... But in the backtrace no latte code is shown...

**Comment by pecigonzalo** [comment]
@psifidotos Pager, Active Window Control, User Switcher do not crash with anything else, this seems related to Latte, I believe you are being too quick to close this issue.

**Comment by psifidotos** [comment]
The fact that an applet doesnt crash plasma panels, doesnt mean that an applet doesnt have crash bugs..

If you can reproduce this in your system first try to remove all related applets... leave only the Latte plasmoid...

Does it crash?
Is the same backtrace?

this bug is closed until it is opened again... i like keeping the users reporting motivated and at the same time I dont like new users showing bugs and crashes in the issues page until they are really confirmed as latte related... if you run the closed issues there are plenty similar backtraces that all are applet related and not latte related

**Comment by pecigonzalo** [comment]
Even then, if plasma panels do handle the crash without completely closing or closing the applet, shouldn't Latte handle the applet the same way?

**Comment by psifidotos** [comment]
> Even then, if plasma panels do handle the crash without completely closing or closing the applet, shouldn't Latte handle the applet the same way?

I dont know any code in plasma that can do that... if an applet is crashing then the plasmashell will crash also...
If an applet doesnt crash a plasma panel that doesnt mean that its code doesnt create crashes in other programs... When the users report crashes from applets the series of events is the following:

1. First we must identify which applet is this
2. Then we look at its code and see if its code has some issues or Latte can handle the situation (there are cases that the developers updated their implementation)
3. Every case until now was a faulty implementation from the applet side... 
4. If it is Latte fault of course and we will fix it but this isnt the case in most times...

dont forget that Latte is not a plasma panel is doing a lot more things and provides a lot more features... so your question could be also reversed... Should we drop Latte features because there are some faulty applet implementations or point to their developers the issue and update their code in order to support Latte ?
 
so, did you find which applet creates these crashes?

**Comment by pecigonzalo** [comment]
No, I dont know how to debug applets, did you? I mean if you cant run applets the Latte Dock is not really that useful.

**Comment by psifidotos** [comment]
> No, I dont know how to debug applets, did you? 

yes of course... you isolate them one by one and find which one is it...
1. you start Latte with only one dock containing only the the Latte plasmoid... you try to crash it...
2. if it doesnt you add a second applet and try to crash it again...
3. if it doesnt you add a third applet etc etc... until you find which on is it...

>  I mean if you cant run applets the Latte Dock is not really that useful.

we live in a free world, everyone can think and believe whatever he wants to...

**Comment by psifidotos** [comment]
@slagiewka if you produce also backtrace please upload it here in order to confirm that this is the same issue and not something totally different... if you can reproduce it, it would be also nice to help us find the applet that creates this instability...

**Comment by psifidotos** [comment]
@audoban have you noticed crashes when using Latte in your multi-screen environment?

**Comment by audoban** [comment]
I dont have any crash
