### ISSUE TITLE
Sometimes latte dock will fail to autostart

### ISSUE THREAD

**Issue by AdamEdry** [psifidotos/Latte-Dock#570]
Kubuntu 17.04
KDE Plasma: 5.9.4
KDE Frameworks: 5.31
QT: 5.7.1
Latte-dock: 0.6.0-1

I have an autostart entry for latte-dock
Here is the [.desktop file](https://github.com/psifidotos/Latte-Dock/files/1106220/latte-dock.txt).

Sometimes latte dock will fail to autostart when logging in.
I looked in `~/.xsession-errors` and found the following:

```
ksmserver: Starting autostart service  "/home/adam/.config/autostart/latte-dock.desktop"
.
. some lines later
.
ksmserver: autostart service "/usr/bin/latte-dock" finished with exit code  11
```

I can't pin down exactly what is different between logins where this happens and where it doesn't and I also don't know what exit code 11 means. Hopefully someone here can help

**Comment by psifidotos** [comment]
Possible a crash but without a backtrace difficult what causes it. Personally i dont know how we could get a backtrace in such situation

**Comment by psifidotos** [comment]
There are discussions around these days that plasma autostarts had some issues lately

**Comment by AdamEdry** [comment]
I've seen mention of using ddd on the FAQ here. Would id be possible to somehow wrap latte in a ddd + start call in autostart? perhaps with an autostart script?

I have 0 experience with ddd so not quite sure

**Comment by rahulprabhakar** [comment]
Even i am experiencing similar issue since last 2 weeks in Manjaro KDE with **latte-dock-git** package installed from Arch User repository. Last updated on 26th June 2017.

**Observed Behaviour**
Every time i login on first attempt latte-dock will show as a running process in system monitor but dock is not visible. I have to manually kill the process and then run it again from krunner. On second attempt it would show up on the bottom edge as configured.

Error message in Journald log
**ksmserver: autostart service ("/usr/bin/latte-dock") finished with exit code  15**

For last two weeks i have rebuilt latte-dock from source multiple times. During this duration of 2 weeks
 
Plasma Desktop upgraded from **5.10.0** -> **5.10.1** -> **5.10.2** -> **5.10.3**
KDE Framework upgraded from **5.34.0** -> **5.35.0**
KDE Applications upgraded from **17.04.1** -> **17.04.2**
Qt upgraded from **5.8** -> **5.9**

**Current setup**
KDE Plasma version : **5.10.3**
KDE Frameworks version : **5.35.0**
KDE Application version : **17.04.2**
Qt version : **5.9**

This does not appear to be Plasma Desktop issue since **AdamEdry** reported this with 
KDE Plasma: 5.9.4
KDE Frameworks: 5.31
QT: 5.7.1

**Comment by AdamEdry** [comment]
I'm not convinced our issues are related or that my issue is a latte issue.

First off our exit codes are different. rahulprabhakar's is 15 and mine is 11.
I'm going to assume the exit code is simply the kernel signal that ended the program so in that case according to [this](http://man7.org/linux/man-pages/man7/signal.7.html) 15 is SIGTERM and 11 is SIGSEGV (segmentation fault).
If you indeed killed the process manually then it makes sense that the error code is 15 - SIGTERM since that is what ending the process does - sends SIGTERM to the program (if I'm not mistaken).

The reason I think my issue might not be specifically latte related is that I've been getting a seg-fault error half the times I logout, on various programs and not only latte.
I'm currently keeping an eye on it although its hard for me to catch the errors when logging out (since it logs out before I can read them fully or save them).

As for why your dock isn't visible. It is probably a separate issue and should be investigated separately

**Comment by rahulprabhakar** [comment]
Apologies for reporting issue in wrong thread. Deleted comment and logged separate issue.

**Comment by psifidotos** [comment]
@AdamEdry are you using a multi-screen environment?

**Comment by AdamEdry** [comment]
Single screen. I have 2 docks. One acts as my panel at the top of my screen and the other as a dock on the bottom screen. 
not sure if this will help but I've included any latte related file I could find in my ~/.config


[latte.zip](https://github.com/psifidotos/Latte-Dock/files/1114619/latte.zip)

**Comment by psifidotos** [comment]
I just show that you are using 0.6.0, is it possible to check 0.6.2 ... we have fixed 4-5 crashes between them...

**Comment by AdamEdry** [comment]
I'll try to update and see if the problem persists

**Comment by psifidotos** [comment]
@AdamEdry not reporting back means that you have no problem with this now ?

**Comment by AdamEdry** [comment]
It hasn't happened on login since the update, however I've had less time to use that computer so I was waiting to be sure. Also seem to have other crashes. But I guess those may be a different issue so we can close this one.

Thanks for your help!
