### ISSUE TITLE
Prevent icons or windows from being placed behind the panel?

### ISSUE THREAD

**Issue by introlinux** [psifidotos/Latte-Dock#578]
The only option that prevent windows (not icons or thumbnails) from being placed behind the panel is "Always visible". In the other options does not make much sense, except in the "Dodge Maximized" option.
It would be great an option for preventing icons or windows from being placed behind the panel.

**Comment by introlinux** [comment]
It is for avoiding for example this situation where the user must know the short cut alt+left_clic+drag or other method to move the window:

![screenshot_20170701_104653](https://user-images.githubusercontent.com/12085920/27760547-a9cce116-5e4a-11e7-8311-59b5023828e4.png)

**Comment by psifidotos** [comment]
In plasma this is called "Windows Go Above" and having talked a bit with @audoban we had decided to not support the case. There are alternatives in order to avoid this somehow. If you set any dodge visibility mode for the top dodge the previous screenshot shouldnt occur.

What visibility mode have you set for your top dock?

**Comment by introlinux** [comment]
This is my visibility configuration.
![config](https://user-images.githubusercontent.com/12085920/27761262-cf8fc5ae-5e58-11e7-9c0b-d4dc73ac3d1f.jpg)

**Comment by psifidotos** [comment]
If you set it to Dodge Active does the same problem occurs?

**Comment by psifidotos** [comment]
My mistake... you have set dodge maximized but the window in the screenshot isnt maximized...

So the alternative for you woyld be to use any other Dodge mode in order to hide your top dock... what you probably wanted is the top dock to be always below windows but i dont think we will provide that in the future

**Comment by psifidotos** [comment]
@audoban do you agree on the above?

**Comment by introlinux** [comment]
Exactly what I wanted is to be always below windows except in maximized window (because you need all space possible).

Any way, what about icons/thumbnails/files in the desktop? Are they managed by Latte dock or the desktop is controled by another program?

**Comment by psifidotos** [comment]
> what about icons/thumbnails/files in the desktop? 

all these are configured through plasma from its systemsettings or from the various apps that you are using. You can also remove your top latte dock and add at its place a plasma panel and set it to be Always Below Windows. To do that you right click on your desktip,Add Panel

**Comment by introlinux** [comment]
I'll try what you say. Thanks.
