### ISSUE TITLE
Folder view animation

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#58]
I noticed that, with Applets size set to 48 px
and zoom on hover at 50%
the animation is not smooth

while everything runs smoothly if Applets size set to 64 px

**Comment by psifidotos** [comment]
this is because the Folder View is not using the same icon mechanism as our dock. The plasma's default icon mechanism creates jumps from 16,24,36,48,64  nothing in between... Above 64 it works ok, so this is also a folderview concern to take care...

Personally my folder view I lock it in order to not zoom. Even with 64px size if you have set a big zoom factor then the animation is broken because the FolderView changes its layout to a list of records instead of a single icon....

**Comment by psifidotos** [comment]
I found a way to hack a bit this applets!!! :)
hehe... the animaton now is smooth... only issue is with the folderview to calculate correctly its length in order to play the animation smoothly... 

I had implemented a heuristic algorithm to identify applets that use the default plasma behavior for showing PlasmaCore.IconItems and when clicking to show their pop ups... I used that in order to draw a fake Latte.IconItem above these applets that can provide us with smooth animation!! ;)
