### ISSUE TITLE
[Feature-request] Implement a mechanism to restart the dock in case of a crash.

### ISSUE THREAD

**Issue by libookami** [psifidotos/Latte-Dock#592]
This bug is a request to implement the ability to restart Latte in case of a crash. I copy what i wrote on the other thread just to have it here for the record:

>Allow me to explain: Now that i use Latte and my only kind of panel, sometimes a plasmoid can crash and take down the whole panel with it. This used to happen sometimes with the regular plasma's panels but in case of crashing they was able to restart themselves. With Latte a few times has happened the same but it doesn't recovers itself. Fortunately is easy to open krunner and launch Latte again.

>I searched a bit on google and found this:
>https://stackoverflow.com/questions/696839/how-do-i-write-a-bash-script-to-restart-a-process-if-it-dies/697064#697064

>So i created this small script and indeed, Latte restarts itself unless it ends gracefully:
```
#!/bin/bash

until latte-dock; do
echo "'latte-dock' crashed with exit code $?. Respawning.." >&2
sleep 1
done
```

>I tested this sending the signal SIGSEGV to latte.

I consider this would be a good idea because novel users may get confused if after a crash (for any reason) they're not able to see their launcher anymore, although it's easy to launch it again from krunner.

**Comment by psifidotos** [comment]
unfortunately, the above script isnt always working... the above script checks if the output of the latte-dock process contains, the specified string... but in case the bash has been translated then I think it wont work...

one more thing, the latte-dock executable can have parameters, -d, -h, --graphics etc...
the script cant follow that... so the only way I can find to work this is to have two different desktop files (because there is also the autostart situation). The first desktop file will be the current one, the second desktop file could provide the mentioned functionality...

**Comment by psifidotos** [comment]
ok... I add this.. so I decided to use one desktop file pointing to latte-dock.sh... this is the script that every 2secs checks in latte is running... executing from app launcher or krunner it executes this script to run Latte... 

if we need debugging etc... the user can still use directly from command line: latte-dock -d ....

For  a user to enable this in autostart (if he is using an older version) must disable and enable again the autostart from the Tweaks page...

@JenaPlinsky I think you were asking for something like this in the past, if you have time please check... :)

**Comment by psifidotos** [comment]
this is how it should look...

![image](https://user-images.githubusercontent.com/2216474/28911615-c6600caa-7839-11e7-9c2a-cba765877bbc.png)

**Comment by psifidotos** [comment]
when latte-dock.sh is running,it is the process that should restart latte

**Comment by psifidotos** [comment]
Ok... update on this... I used KCrash instead for this... So the bash script is not needed at all and KCrash is going to restart Latte in every crash and at the same time open DrKongi for info about the crash ...

**Comment by libookami** [comment]
Thanks a lot!. Just updated from git and tried sending SIGSEGV and works perfectly. It's a great improvement for people who wants to use latte as it's only kind of panel.

**Comment by JenaPlinsky** [comment]
@psifidotos  How can i test the new automatic restart feature after a crash?

Right now that I want to test this feature I have no more crashes Grrrrrrrrrrrrrrrrrr :)

**Comment by psifidotos** [comment]
kill -SIGSEGV latte_process_id

The latte process id you can find it with ksysguard

**Comment by JenaPlinsky** [comment]
Here's how I do not observe crashes anymore !!!
Maybe it's due to the new features ... is this right?
... if so, I have to say that it works so well that I did not notice anything !!!

But when does this mechanism intervene, are some useful information stored somewhere?

How do I notice that there was a crash?

**Comment by JenaPlinsky** [comment]
Maybe at this point a logfile might also be useful

**Comment by psifidotos** [comment]
When a crash occurs in your systemtray you will e find an extra icon to open the kcrash

**Comment by douglasg14b** [comment]
It would be nice to have a way to restart it, successfully, on a regular basis.

When KDE stops functioning correctly (which is quite often), restarting plasmashell usually fixes it but latte-dock gets stuck on screen and doesn't work properly anymore.

Sometimes `latte-dock --replace` will work, but then you have to Ctrl+C to kill the command since then run latte-dock separately. Which is kind of a pain. Sometime --replace doens't work and the processId needs to be manually killed.

Having a built in way of restarting latte-dock when it no longer functions correctly would be very helpful.

**Comment by psifidotos** [comment]
This is already implemented and Latte is using the same way plasma does

**Comment by psifidotos** [comment]
If it doesnt work properly in some cases is either kcrash or qt responsibility
