### ISSUE TITLE
Pinable folderview

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#606]
For those like me, that are using foldersview docked on Latte, It would be very convenient, exactly as it happens for the launchers, have the ability to associate one or more folderview with a particular task, for example 

- **Global** activitiy
    - [Web-folderview] [Office-folderview][ Drawing-Folderview] [Photography-folderview] [VideoEditing-Folderview] [Cinema-Folderview] [Develop-Folderview] ...launchers and tasks
- Drawing activity
    - [Web-folderview] [Drawing-folderview] [Photography-folderview] ...launchers and tasks
- Video activity
    - [Web-folderview] [VideoEditing-Folderview] [Cinema-Folderview] ...launchers and tasks
- Develop activity
    - [Web-folderview] [Office-folderview] [Develop-folderview] ...launchers and tasks
- Game activity
    - [Game-folderview] ...launchers and tasks

This would make the dock even more activity centric...
I think that. Implementing something like this should be proposed to the plasma team .... right?
[Brainstorm](https://forum.kde.org/viewforum.php?f=83) is the right place for this ?

**Comment by psifidotos** [comment]
when dynamic layouts are landed you will be able to have completely different Latte layout for each Activity that means widgets, settings, etc... everything... Changing into an activity you are going to be able to set anything you want for your docks/panels and this is going to be changed only at that specific layout... This is going to be landed in master at around 2 weeks... What is not possible is to share things between different layouts, such as launchers, universal docks etc...

**Comment by psifidotos** [comment]
duplicate for #577

**Comment by psifidotos** [comment]
@JenaPlinsky if you want to provide feedback for the new layouts... the code is ready... you can try branch **newLayouts** but be sure you **make a backup** before!!!! Just in case!!!

Functionality provided through the layout manager:
Defaults -> re-adds the known presets if the there arent present because the user removed them
Import/Export -> import/export your layouts and your configuration
rename layouts
set different colors to layouts
assign activities for layouts(the code for aumatic changing hasnt been implemented yet, it is a matter of days)
switch into a layout(make active a different layout)
copy layout
delete layout

apply button -> applies all the changes and the layout manager window remains shown
ok button -> applies all the changes and the layout manager window closes
Cancel -> undo all changes concerning layouts and close the window

**Comment by JenaPlinsky** [comment]
Very happy to test it
