### ISSUE TITLE
tooltip text as folder name instead full path

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#631]
![spectacle s12090](https://user-images.githubusercontent.com/24593950/28745977-f02b3aa0-7483-11e7-885c-10ed1800bf91.png)

I usually customize the folder view title ....
But why not extract the last directors of its path?
So, its the tooltip would be clearer and more compact

**Comment by psifidotos** [comment]
Latte is just using the titile the plasmoid provides nothing more... so this should be implemented in the plasma folderview

**Comment by JenaPlinsky** [comment]
... irrespective of how the title was set in the folderview dialog box ...so,  doing a simple text substitution by deleting all that is before the slash is not possible ?

**Comment by psifidotos** [comment]
it is possible but it is also one more workaround for folderview and I dont know how many workarounds for folderview we will add in the end...  

a fast workaround would be in the title has an ":" show the title as it is... e.g. "activities:/current"
in other case show only the last part after "/"

**Comment by psifidotos** [comment]
ok... I just checked... if the user sets a different title in the folderview that is respected by the plasmoid title...

so what you are proposing is a different default behavior for folderview, instead of showing also the precious directory, to show only the current directory used...

so this is definitely a feature request for the plasma dev team...
