### ISSUE TITLE
[v0.6.x] - shuffling launcher icons

### ISSUE THREAD

**Issue by LuciferWatson** [psifidotos/Latte-Dock#659]
Latte Dock 0.62

The "Show launcher when not running" option is selected for any programs, either opening or closing a program shuffles its position in the dock.

**Comment by psifidotos** [comment]
yes, it is known for 0.6.2 version... We believe that we have solved this for the 0.7 version (master branch) at least we will provide the same behavior with plasma taskmanagers. Only issue is that 0.7 version which is going to be released in a week in plasma 5.9 compatible and above...

Unfortunately for the 0.6 version because it relies at a different launchers mechanism than the 0.7 we cant do anything

**Comment by LuciferWatson** [comment]
I'm running Tumbleweed, so hopefully the repository will be updated shortly after release.

**Comment by psifidotos** [comment]
@LuciferWatson usually it does... I dont maintain any repos (I dont know how long will take to @audoban 
 to update this) but I am optimistic. openSUSE community-packagers are very active with Latte Dock https://software.opensuse.org/package/latte-dock?search_term=latte+dock

**Comment by psifidotos** [comment]
I suppose this must have been improved a lot with v0.7 version...
