### ISSUE TITLE
Launchers glitch

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#664]
Sometimes I observe ( at minute **1,50** ) a glitch when a launcher is activated
Is it possible to clean it?
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1217739/video.zip)

**Comment by psifidotos** [comment]
it is even though it needs a lot of testing....

info (based on the libtaskmanager way of implemented):
1. when a launcher in activated, the new window immediately is activated
2.1 the launcher delays its removal until the bouncing animation has ended and afterwards it removes itself
2.2 the time of the bouncing animation end can not be done with a signal is done with having almost the same time to happen
3. If the launcher removal lasts more than the bouncing animation then this glitch is appearing. On the other hand if the launcher removal takes place too early then the bounce animation breaks

only thing that can be done is to make the removal a bit faster than the bouncing animation but this needs a lot of testing in order to not break the bouncing animation

**Comment by psifidotos** [comment]
@JenaPlinsky please test branch **fix664** and tell if it improves the situation

**Comment by JenaPlinsky** [comment]
@psifidotos  ...to me it seems that the fix works very well I also tried changing the speed animation and did not notice anything strange

**Comment by JenaPlinsky** [comment]
Sorry i've tested the master branch it was already merged?

**Comment by psifidotos** [comment]
Yes,  I merged it just before the 0.7 release :-)

**Comment by JenaPlinsky** [comment]
By the way, besides being a great programmer !!!!!!, 
...I have to say that you are also a great Art Director and your presentation is absolutly Amazing 
Woow I like it a lot !!!! It honors your work

**Comment by psifidotos** [comment]
@JenaPlinsky :) thank you!!! :)

**Comment by JenaPlinsky** [comment]
a curiosity
Do u know how many people , are you using Latte ? is it growing ?

**Comment by psifidotos** [comment]
> Do u know how many people , are using Latte ? is it growing ?

I have no idea! I dont know how we could obtain such metrics
