### ISSUE TITLE
[feature request] Top Panel Workspace Scroll

### ISSUE THREAD

**Issue by divinae** [psifidotos/Latte-Dock#671]
Could you implement something like gnome Top Panel Workspace Scroll extension (https://extensions.gnome.org/extension/701/top-panel-workspace-scroll/) ?
With this extension I can switch destkop with mouse scroll, when my cursor is on panel (except items like volume indicator).

**Comment by psifidotos** [comment]
I think the activities/desktop widget provides that, and you can also change by scrolling on the desktop if you want

**Comment by divinae** [comment]
its easier and faster to scroll on all of panel space versus little widget + Pager and desktop scroll have litte bug - there is loop after scroll down on last desktop( i have Desktop navigation wraps around on)

**Comment by psifidotos** [comment]
ok.. I will have to think it over... not the implementation side but rather the side effects and if there is a big demand for this...

**Comment by michaldybczak** [comment]
If this feature would be implemented then as a setting that has to be manually turned on. It would be too confusing to have that by default. Also, people may want to use scroll in a different way. Workspaces are not so widely used in practice but when you do use them, you have various ways of switching them in plasma:
- key shortcuts (can set custom ones - ctrl+alt+arrow it's what I use)
- hot corner triggering desktop overview or desktop cube
- mouse gestures (with mouse gestures package)
- mouse scrolling on the widget/desktop
- clicking on widget

Actually, I saw somewhere implementation (openbox with tint panel?) when on a mouse scroll you would change desktops. That was so annoying because it was easy to switch them accidentally.

Anyway, it seems like this feature has quite wide variety of methods you could use. I understand that coming from gnome you may have some habits, but I also had to give up super key switching to overview (super can't be assigned to overview in Plasma). I just must accept that Plasma works a bit different so I just set my custom shortcut ctrl+x that  triggers overview. It's not as good as having super key for that but it's workable.
