### ISSUE TITLE
0.7 rocks! Some small issues to polish

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/Latte-Dock#688]
1. After update and a bit before it, calling dock to show became almost impossible. I moved mouse down and nothing. So now I changed showing delay to 0 and now it finally works normally. It seems like this delay option became broken, because any value above 0 just makes dock not to show till you minimize everything.
2. Not sure if that's general issue or just specifically mine system issue, but before, super key didn't work for start menu till I didn't set some alternative shortcut and then both (super and custom shortcut) work. This thing is, it worked that way on system panel. On Latte super never worked and it still doesn't work. Now when I deleted system panel and use Latte for dock and panel, this thing became more important. Anyway, now I can only use specified shortcut.
3. Some widgets seem to have little issues, like: redshift icon becomes invisible after a few seconds on latte (work well on system panel), but that maybe tried to desktop theme? Also, any start menus put on latte won't get "alternative" option on right click, at least it didn't want to work that way today.
4. Some icons on latte-panel seems to be to on the screen edge (like window buttons from Active Window Control). Also, by default my panel wasn't on the right edge in justify mode (there was a gap) but after playing with settings, turning them off or to zero and then on and 100% again somehow fixed it (for panel).
5. Somehow Active Window Control slightly shows different placement of application icon, which is too close to window buttons, this doesn't happen on system panel. I guess it might be this widget issue so I should report it there in hope it will be fixed.
6. Please don't use "change size of applets when needed" as default! It's crazy and I was SURE that latte is bugged because it was resizing icons to some tiny sizes every time I put it on top position. It was so annoying and problematic. Luckily I finally found this insane setting and it was on, although dock was newly created.
7. I wish that there would be some way to define spacer's width, because they seem to be too wide for my taste.
8. I can't set my latte-panel in right size. 32px is too big, 24px is way to small. Why those values jump discretely? 30px or maybe 28 would do for me, but so far Latte won't let me.
9. I am a bit confused by Layouts Configuration. I set different layouts for activities and it works but wanted to rename or create new ones and couldn't find any buttons for it. Also, had to figured out by trial and error how to set activities (few clicks on the the empty panel, no simple menu to unwrap, this was confusing), add new layout, change it's name. It's not bad but defenitely not intuitive as yet and needs to be tweaked. I feel like Layout confiscator UI is too simplistic so it doesn't hint us what is possible and how. It took me a while to figure out that "copy" is to create a new layout (weird, no "new layout" button", also that I have to double click on spaces to set activities and names.

During hours of playing with Latte setting, few times it crashed but it restarted immediately but that was on day one, now it seems to be stable so no real issue.

So far problems are minimal and in general dock/panel it's awesome! You created this dock in such short amount of time and it quickly overgrew competition. Latte is now for me an essential part of Plasma Desktop and I would like to see it by default in DE.

**Comment by psifidotos** [comment]
ok, some are valid, some are very difficult to handle...

1. there is a chance that this is not show option fault, do you have a video?... have you disable all touch gestures from plasma system settings?

2. https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-can-i-use-my-super-key-to-open-the-app-launcher

3. can you show me a screenshot for redshift to understand? The Alternatives option is present only on Latte Edit mode, that is when showing the Latte settings window

4. need a screenshot to understand the issue

5. need a screenshot

6. it is default because the Latte is used mostly as a dock, for which it makes sense... If I remember correctly I disable it in case the user sets the dock to behave as a plasma panel (that is Justify, always visible, 100% background )

7. you can... Latte 0.7 provides its own spacers and you can add from the Tweaks page... You can set a percetage or pixel size for them... In edit mode you can use your mouse scroll whell in order to change their size

8. the sizes have been chosen in order to try to show always icons that dont blur based on what themes provide... usually, 16,24,32,48,64... but it could make sense to add such way to alter the icon size in pixels +-1 when Latte behaves as plasma panel and the automatic icon size shrinking is disabled... that is a good idea to test actually...

9. rename: double click on the Layout name and click apply afterwards...
new: yes, that makes sense... a New button to add a new default layout
the way we used was that the user can press Defaults and the the default layouts are added in order for the user to build upon

> During hours of playing with Latte setting, few times it crashed but it restarted immediately but that was on day one, now it seems to be stable so no real issue

this needs a backtrace that shows exactly what crashes, most of the time are plasmoids issues and not Latte

please for bug issues or improvements it is better in the future to add separate threads in order to keep the discussion structured...

> Latte is now for me an essential part of Plasma Desktop and I would like to see it by default in DE.

thanks a lot...

**Comment by psifidotos** [comment]
concerning (8), I added a commit in order to be able to +-1px for the icon size in the following case:
- when the automatic shrinking is disabled and we are in advanced mode in Latte settings

**Comment by michaldybczak** [comment]
1. Strangely, in this and next sessions the bug doesn't appear... so I can't show it, but I definitely had issue with that since some time. It's possible that some process gets corrupted and only then this thing shows up. I've been seeing such small problems many times on plasma panel (something works, like super key  and then randomly it stops, after reboot it works well again).  Anyway, since I can't reproduce it at will and since it's random, I understand that you would have troubles to understand what is happening so forget about it right now. It's more likely Plasma issue with processes reading configs.

2. Thanks, it works! Awesome!

3. Here is screenshot during latte configuration (fade away state - that's where spectacle does screenshot) and you can see that nothing is there, just empty space.

http://imgur.com/LkD1XTI

Here is next screenshot in normal state, again empty space:

http://imgur.com/BRIfo4l

3a. Another issue showed up, if needed we can move it to the next topic. Do you see this white shadow/cloud around black icons on the last screen (above)? If I switch to dark theme and icons are white, they are crisp, but when I change to theme with ligh panel (like breeze light and similar), I get such irritating white shadow around black shapes.

4 and 5. Here is the screen:

http://imgur.com/JOD013W

When I add launcher on the beginning (farthest left), than I get some space like on screens above. When my first widget is Active Window Control and I set buttons to be first, I see then by the edge of the screen. The same edge effect is with clock when I remove redshift widget from it's right corner position.

But that isn't an issue if I just use spacer and adjust its width manually to few pixels, so I guess you can forget about it, but I think that system panel adds some small distance on the panel edges. Active Window Control produces very slightly different results with the same settings then on system panel - but that might be caused by different sizes of a panel and latte-panel and how icons are scaled. Anyway, I think we should just leave it for now, I'm sure you have more important things.

6. Yeah, setting it off in justified (panel) mode seems to be a good idea, because this tweak just drops like a bomb on user and for the first time it's not clear what is happening, why suddenly everything is shrinking. You already implemented loosing options where there is no task manager (in upper panel with global menus) and that's a great feature, so settings that are not applicable anymore are not confusing. It shows how carefully you thought all this through. This is amazing! Most developers are oblivious to such design decisions but you focus on user experience and care about it - that is why latte became so awesome so quickly!

7. Didn't know that. That's really helpful. I added spacer with 10 pixel size and the edge button placement is fixed that way. I moved invisible redshift before system tray and than the same 10 pixel sized spacer on the farthest right so the clock is not by the edge anymore. Now it all looks fantastic!

http://imgur.com/hMhKcsq

Nice spaces on the left and right side. Such small thing but it makes a huge difference. The whole look is now consistent and professional.

Manual pixel size of spacers is so useful. I love latte and whole plasma for such deep and small settings. The downsize is, it's sometimes hard to find them or understand what they do, but I guess it comes with territory. You can't have such fine tweaks without some hardships. It also takes lot of time and effort to tweak things with such details but I still prefer to have those options. In other DEs I feel like they were seriously handicapped after the freedom that Plasma allows. Latte dock adds tremendously to that freedom! :)

If I only could add such spacer inside Active Window Control widget... But I will contact with AWC developers and maybe they will add some finer tuning options, however although AWC is awesome widget, it's not as well user focused as Latte is. Actually, the whole Linux experience is a bit too raw for many average users because most Linux things is not developed through the average user experience (like windows or mac is). It's so incredible when we find project like Latte who is different and do cares about small things that matter for users. It just shines!

8. Yeah, I would love to have option to refine it a bit more. There are so many scaling possibilities and not with all of them things look good. Having option for more detailed scale will help to adjust that. Thanks for the commit :). Did I already mentioned how Latte rocks ;)?

9. Yeah, new for default, copy for copying chosen layout for some alternate base.


I think you addressed most of my points so that was a quick help :). Basically it was left to **3a** - this white halo around dark graphics, but like I said, I can start a new topic for this, unless it's easy and quick fixable? And redshift icon being invisible (in both, light and dark themes). However, when I moved it before task manager, it doesn't matte. Also, in next Plasma version redhift abilities will be implemented in system so it no longer be needed, so in the end issue is not big and can be lived with.

**Comment by psifidotos** [comment]
3. Latte uses some in-house heuristics in order to provide smooth parabolic effect etc... The issue was that redshift cant follow that heuristics from our side... I blacklisted and now it works ok even with the parabolic effect. an alternative could be to enable redshift in your systray... This is how I am using it...

![image](https://user-images.githubusercontent.com/2216474/29750146-474fff84-8b43-11e7-9e96-c23cc9fe88a3.png)

3a. other users repoted this also, so now when the user uses to show solid background only when there is a maximized window in the screen the applet shadows are respected... In Appearance page in advanced mode the user can enable/disable the applet shadows and even configure them totally with colour, transparency, size... these settings for now on are respected...

4,5 It is called Fitt's Law (https://en.wikipedia.org/wiki/Fitts%27s_law) and plasma panels and desktop are doing their best in order to support it... If they dont it is considered a bug for plasma and Latte is doing its best to support it also... So Latte when used in Justify mode, 100%max length then in that case it is providing Fitt's Law for the first and last applets in the Justify mode... Of course I added the Latte spacers in case the user prefers better visual effect than following the Fitt's Law

9. unfortunately this will have to wait for Latte 0.8 because it adds a translation string that didnt exist before by I might consider it too important and add it... Either way full translations are provided only for 3-4 languages for 0.7 version...

>  Also, in next Plasma version redhift abilities will be implemented in system so it no longer be needed, so in the end issue is not big and can be lived with.

for Latte 0.7.0 using redshift through the systray is the only solution... for 0.7.1 it will be fixed...

**Comment by psifidotos** [comment]
I think that have been addressed most the issues this can be closed...

**Comment by michaldybczak** [comment]
How many things I said awesome? Awesome :D

3a. Not sure if I understood. You mean,you fixed it and I just need to wait for update on my disrto (using Manjaro)?

3. I switched to sys tray redshift (didn't know that you can, using Plasma so long and I still discover new things ;P).

4,5 ok, will read on it, but I'm really happy with the effect I have with custom sized spacers.

9. No problem, there is no pressure. It seems reasonable to add it to another release since it's a new feature.

I have some additional questions but I ask them in comment section in your blog.
Thanks!
