### ISSUE TITLE
[feature suggestion] reverse icons color when panel background hidden

### ISSUE THREAD

**Issue by alxlg** [psifidotos/Latte-Dock#701]
I really like the option to hide the background of the panel but I need a very light wallpaper to make the monochrome icons visible. It would very useful an option to reverse the color of monochrome icons (aka using the bg color instead of text one) so black icons would become white when the panel background is hidden.

I know this could be difficult to implement.

**Comment by psifidotos** [comment]
sorry not possible... only solution is to set an applets shadow that provides you with the needed  contrast

**Comment by alxlg** [comment]
This is the second time you close a feature request by me replying it's impossible and then come with a solution after some months :)

You should really consider to keep these requests open until you find a solution and then happily close them :)

**Comment by psifidotos** [comment]
> You should really consider to keep these requests open until you find a solution and then happily close them :)

at the time I couldnt consider any solution...
closing issues that I dont consider technologically possible keeps me focused and keeps also the issue page clean... so a solution for this #905  was discovered almost accidentaly because a ColorOverlay for all the panel did the job (http://doc.qt.io/qt-5/qml-qtgraphicaleffects-coloroverlay.html). If we wanted to paint specific applets with different colors, or to keep the colourful items untouched then this wouldnt work.
