### ISSUE TITLE
Icon disappear/reappear when a pinned application is launched

### ISSUE THREAD

**Issue by rokups** [psifidotos/Latte-Dock#72]
Currently when application that is pinned to dock is launched icon of that application moves out of dock and moves back in when application starts. This causes entire dock shrink and expand in width. Could we get an option to disable this animation so icon of application remains in the dock? As a result when application launches white|blue dot should just appear below icon and that's it.

Thank You

**Comment by psifidotos** [comment]
> Currently when application that is pinned to dock is launched icon of that application moves out of dock and moves back in when application starts. This causes entire dock shrink and expand in width. Could we get an option to disable this animation so icon of application remains in the dock? As a result when application launches white|blue dot should just appear below icon and that's it.

unfortunately this removal and addition is because of plasma's libtaskmanager.
I could create an option to disable the animations but I dont know what would happen when the window opened is not categorized correctly to the launcher...

**Comment by rokups** [comment]
Sounds like it should be a feature request to upstream then?

**Comment by psifidotos** [comment]
you can check: https://github.com/psifidotos/nowdock-plasmoid/issues/9

it has been already reported: https://bugs.kde.org/show_bug.cgi?id=368386 but dont except something in the near future...

**Comment by psifidotos** [comment]
found a fix for this, it is in master!!!

**Comment by rokups** [comment]
Amazing! Didnt think we would get it. I tested it some. Dolphin for some reason still disappears for short amount of time when launching. Quitting dolphin keeps icon in the dock as it should. Not sure if it is of any relevace but i have custom icon set for dolphin, although setting it to default one didnt help.

**Comment by psifidotos** [comment]
You could see at, .local/share/applications if there are any launchers in there for these progams and try to remove them...

My guess is that libtaskmanager delays its updates, i dont know how able we are to improve more the workaround... i havent such launcher yet in my system to debug....

**Comment by rokups** [comment]
It seems that launchers in that dir are of no relevance. This seems to happen to some applications that are have launchers and to some that dont have.

Could you elaborate what workaroudn is this? Maybe point me to commit?

**Comment by psifidotos** [comment]
https://github.com/psifidotos/Latte-Dock/commit/41395ee5c126b86dbb3085b57476816cedf2cc8e

Some internals, we use plasma libtaskmanager as a tasks model. This model works as following:
[1.Launcher] <-> [2.Startup] <-> [3.Window]

for any change from the above additions and removals are happening and step 2 may not occur... In plasma taskmanager this is not shown because it doesnt have any add and remove animations... A few weeks now we were able to reprocude correctly the plasma libtaskmanager behavior, meaning that for **"None"** animations our add and remove animations become with duration = 0 and that creates the same experience with plasma.

**_Workaround for add/remove animations_**

the new approach is that we are blocking all add/remove animations (set duration:0) for all cases except on specific exceptions.

1. A launcher is added and there is not a relevant window
2. A launcher is removed and there is not a relevant window
3. A window is added and there is no launcher for it
4. A window is removed and there is no launcher for it

I suppose that issue you are reporting falls onto case (2)

you can look at our own latte plasmoid the file called TaskDelegate.qml. At the end there is a ListView.onRemove transition which makes the check for (2)...
we could do a workaround in case the user clicks the launcher to open the window but in case the user runs the application in other way e.g. from app menu the behavior would remain the same...

**Comment by rokups** [comment]
Have you considered having a proxy model (much like ones used for sorting) and altering adding/removing behavior? Maybe that would be easier way to work around this behavior?

**Comment by psifidotos** [comment]
be free to submit patches... as long as the situation is improved and no functionality is broken... we will accept them...
