### ISSUE TITLE
Why is Latte-Dock constantly consuming CPU time?

### ISSUE THREAD

**Issue by j0hannes** [psifidotos/Latte-Dock#728]
In terms of accumulated CPU time it even outreaches Xorg and kwin_x11. Most of the time it is auto-hidden in my setup. I have disabled animation and transparency.

**Comment by psifidotos** [comment]
Are you using a menu in latte with combination with electron apps?

**Comment by j0hannes** [comment]
No, I don't even know what these are :)

**Comment by psifidotos** [comment]
Show me a screenshot from all your latte docks instances

**Comment by j0hannes** [comment]
That's the only one:

![screenshot_20171008_161411](https://user-images.githubusercontent.com/3944397/31317568-dd0ac22c-ac43-11e7-987d-08c9c9f69785.png)

**Comment by psifidotos** [comment]
Nothing suspicious... what latte version are you using?

**Comment by j0hannes** [comment]
```
community/latte-dock 0.7.1-1 [installed]
    A dock based on Plasma Frameworks
```

**Comment by psifidotos** [comment]
Does this occur if you use also the Default layout?

**Comment by j0hannes** [comment]
It does. I've seen the process on top position when my machine was otherwise idle since I tried it the first time.

**Comment by psifidotos** [comment]
so you have tried different things and at all cases Latte uses the maximum cpu?

1. remove plasmoids until one found that creates this issue
2. use the five provided layouts to test it if the problem occurs at all cases
3. change screen edge for the dock, visibility modes etc. and see what happens
4. use app menu inside the windows and not external in a plasmoid or panel

**Comment by j0hannes** [comment]
It is not that it would stress the CPU, it just constantly does something even when it's hidden and that makes it more CPU-hungry than other, far bigger system processes.

I tried your suggestions and removed the system load viewer which lowered CPU consumption to almost zero. I guess also removing the system tray I would give me zero.

So now my question is: Why are plasmoids rendered even if not visible? When using the standard panel with the same plasmoids, I've never seen any noticeable CPU consumption.

And I don't get your number (4).

**Comment by psifidotos** [comment]
> Why are plasmoids rendered even if not visible? When using the standard panel with the same plasmoids, I've never seen any noticeable CPU consumption.

ok, now we have an understanding... Latte uses a different technique than plasma panels to hide the dock. Plasma panels are moving the entire window and put it out of screen, what qt is doing in such cases is that windows that are out of screen are not updated graphically, the moment that re-enter the screen all holded updates are happening. Because plasma panels are not using many animations this isnt noticed because the update is happening instantly.
Latte on the other hand is not moving the window out of screen, it just lowers the contents inside the window and changes its mask in order to be just 1px size at the edge of the screen in order to catch the mouse enter to reappear its contents. In the past before Latte when I was developing Now Dock I had the following issue. before using the mask technique described before I was also moving the window out of screen. The bigest issue was that all the animations concerning window removals etc were played after the window was reappearing even though they didnt have any meaning...

so we used the mask technique that Plank also uses in order to provide our visibility modes...
