### ISSUE TITLE
move Icons from Desktopstyle:folderview

### ISSUE THREAD

**Issue by Tids** [psifidotos/Latte-Dock#737]
When you set folderview as desktop style and enable latte dock as plasma-bar, this bar will overlap with the icons in a corner.
A normal Plasma-bar will move the icon so that they never overlap in some way. that what latte-dock schould also do

![image](https://user-images.githubusercontent.com/18744080/31686916-1036332a-b388-11e7-963c-99209f164e6e.png)
^ this is a bad example. it should not happen

**Comment by psifidotos** [comment]
Unfortunately plasma desktop doesnt expose such functionality and Latte cant do something more about it

**Comment by kupiqu** [comment]
I wish this could be considered by plasma developers and implemented soon, more so now that (1) lattedock has been ported to KDE's infrastructure and (2) it has maintained its momentum for quite long time already

**Comment by Pointedstick** [comment]
@psifidotos, do we have a bug report tracking the issue in plasma-desktop? If not, would you mind filing one? Or even better... submitting a patch? :smile:

**Comment by psifidotos** [comment]
@Pointedstick nice to hear from you Nate! I love your work!

I have just created : https://bugs.kde.org/show_bug.cgi?id=391073 to open the discussion for this.
It is more a plasma devs question if  they will agree for this rather than just implementation. I could try to implement it if the plasma devs agree in any approach they prefer...

**Comment by Pointedstick** [comment]
Excellent, thanks!

**Comment by psifidotos** [comment]
from today all new or unclosed issues should be reported to: https://bugs.kde.org/
