### ISSUE TITLE
@AUTHOR@ in translation

### ISSUE THREAD

**Issue by scootergrisen** [psifidotos/Latte-Dock#767]
I'm translation stuff for KDE and came across a string called "@AUTHOR@":
```
#. (itstool) path: component/developer_name
#: org.kde.latte-dock.appdata.xml.cmake:17
msgid "@AUTHOR@"
msgstr ""

```
https://github.com/psifidotos/Latte-Dock/blob/master/app/org.kde.latte-dock.appdata.xml.cmake#L71

I don't know if this is a mistake but it seems like it should not be in the translation.

**Comment by psifidotos** [comment]
it is substituted by our english names during installation in order to not write them again and again in various places and having to update all these places afterwards...
I dont know... for other projects do you translate also names into native languages?

If you just copy paste it, it should work just fine

**Comment by scootergrisen** [comment]
If @AUTHOR@ is a variable then i would assume it should not be in the PO files.
And even if the translators should be able to translate the name how could they? The name is not there so how would they know what to translate it to?

I don't think i have ever seen persons names translated in my language to other then what it is originally. Maybe i just dont know about it or maybe its only done in some languages.

**Comment by psifidotos** [comment]
ok... I added directly the developers names
