### ISSUE TITLE
is there an optimal solution for the very populated dock?

### ISSUE THREAD

**Issue by JenaPlinsky** [psifidotos/Latte-Dock#786]
I know this thing is very complicated and requires a lot of work and I do not even know if it's technically feasible ...but I'll throw it there
 .... some time ago we had already discussed this thing but now looking at a video of the Unity dock 
[unity min 0.49](https://youtu.be/GWyntfGeLVs) 
it makes me think that it would be the top to combine the latte's parabolic effect with the  icon's shift 
 when the panel is too populated .... the current dock is perfect !!!! but maybe in the future you could think of an alternative to the shrinking of the icons .... it would be ideal for small screens or if the dock is placed in the shorter side of the screen furthermore, when the parabolic effect is disabled, and with very small icons, the badges are too small

**Comment by psifidotos** [comment]
I can accept patches for providing somethung better

**Comment by JenaPlinsky** [comment]
unfortunately I'm not able to help with the code 
[video.zip](https://github.com/psifidotos/Latte-Dock/files/1540457/video.zip)
This type of animation is written in qml .... can this suggest some ideas?

**Comment by psifidotos** [comment]
this is a question of development hours needed in order to make it work and orchestrate with all parts, something that personally doesnt motivate me...

for any proposals someone must take into account:

1. what happens when there are applets around the plasmoid and the parabolic effect is active?
2. how the user is informed that there are more tasks hidden somewhere or shown differently.
3. how the user accesses those overflowed tasks and how this is animated
4. how the proposed solution interacts with the parabolic effect
5. how the proposed solution wont break the current implementation and will work correctly as an extra feature

the specific video that demonstrates a solution has many design problems in my opinion. But this is not only  a proposed solution thread, is also and a person question (who is going to implement it? as I am not motivated to do this)...

**Comment by JenaPlinsky** [comment]
Of course it is very challenging and certainly would create problems to the excellent state of the current project !!!

... it is certainly not a necessary thing .... I was only curious if it could suggest ideas to someone

**Comment by psifidotos** [comment]
deprecated...
