### ISSUE TITLE
Fork to, take out KF5 dependencies for 18.04

### ISSUE THREAD

**Issue by 3DJetengine** [psifidotos/Latte-Dock#792]
I was looking at [this issue](https://ubuntu-mate.community/t/any-chance-we-could-get-latte-plank-in-the-next-lts/12069/5) in ubuntu-mate 18.04

and was backing the project, but was unsure as to the benefit of the KF5 dependencies ?

-/

**Comment by psifidotos** [comment]
sorry... I dont think this is possible... each KF5 library provides functionality that Latte features need...

**Comment by 3DJetengine** [comment]
apologies @psifidotos I was just on [omea-reader](https://www.ghacks.net/2016/01/21/omea-reader/) and thought 

this could be looking into ?

Does this affect the Qt applications aswell ?

please keep this open until next week cheers.

**Comment by psifidotos** [comment]
> Does this affect the Qt applications aswell ?

There are apps that have two..three different UIs, one in Qt, other in GTK+ etc... but the app must be adjusted to such possibility...
for their underlying libraries.... e.g. Qt3D the only way is for the developer to find an alternative and adjust its app code also to use the alternative library and not Qt3D

> a fork could be called latte-souble I guess.

I dont know... that is of the developers to decide... I would be very surprised if someone could take the Latte code and make it to work without KF5 libraries or Qt5 ones... My best guess is that someone should start from scratch and use whatever libraries needs to and just try to imitate the Latte behavior and UI.

As a small note.... KF5 libraries lift MUCH MUCH burden! e.g. Latte is using the plasma libtaskmanager library in order to have a model for launchers and tasks... Latte isnt doing anything about that, whatever launchers and tasks plasma supports, Latte supports it also directly! ;)

either way I will keep this open to watch over the discussions!! :) hehe

**Comment by 3DJetengine** [comment]
> make it to work without KF5 libraries

yes, but cannot offer up any code myself, bearing in mind there are numerous Kf5 dependencies , 


for example:

[libkf5crash-dev](https://cgit.kde.org/latte-dock.git/commit/?id=78cab65a81551c18ffe9d5fd23c34627aa167e47)  any others offered to list ?

**Comment by psifidotos** [comment]
> any others offered to list ?

what do you mean ?

**Comment by 3DJetengine** [comment]
@psifidotos I guess I am ready to find out what KF5 dependencies there are in Latte Dock ?

**Comment by psifidotos** [comment]
from the README: https://github.com/psifidotos/Latte-Dock/blob/master/README.md

these are the KF5 libs needed...

```
KF5Plasma >= 5.29.0
KF5PlasmaQuick >= 5.29.0
KF5Activities >= 5.29.0
KF5CoreAddons >= 5.29.0
KF5DBusAddons >= 5.29.0
KF5Declarative >= 5.29.0
KF5Wayland >= 5.29.0
KF5Package >= 5.29.0
KF5XmlGui >= 5.29.0
KF5IconThemes >= 5.29.0
KF5I18n >= 5.29.0
KF5Notifications >= 5.29.0
KF5Archive >= 5.29.0
KF5GlobalAccel >= 5.29.0
KF5Crash >= 5.29.0
KF5WindowSystem >= 5.29.0
```

**Comment by 3DJetengine** [comment]
http://piratepad.net/XMiqlBWc4D

**Comment by psifidotos** [comment]
if you are working in Ubuntu system...
by the INSTALLATION file for Kubuntu/Neon the packages needed are:

```
libkf5iconthemes-dev
libkf5plasma-dev
libkf5windowsystem-dev
libkf5declarative-dev
libkf5xmlgui-dev
libkf5activities-dev
libkf5wayland-dev
libkf5archive-dev
libkf5notifications-dev
libkf5crash-dev
libkf5globalaccel-dev
libkf5kwindowsystem-dev
libkf5package-dev
libkf5archive-dev
libkf5i18n-dev

plasma-framework-dev (whatever needed in order to add plasmoids in Latte, access containment features and corona)
plasma-workspace-dev (provides the libtaskmanager)
```
