### ISSUE TITLE
[feature] - Dynamic background and snapping

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#810]
#805 #806 described a more intelligent dynamic background.
One that should also take into account the snapped windows and the case of krunner and yakuake...

After playing with this a bit there are plenty possibilities and many things can be done but I dont want to provide extreme configurability about this...

Currently there are three relevant options:

**1. Force solid background for maximized windows
2. Hide background for not maximized windows
3. Hide panel shadow for maximized windows**

What works very good is to support instead of (1) and (2)
**1. Force solid background whenever a window touches the panel edge
2. Hide background whenever there isnt any window touching the panel edge**

the **(3) choice** could remain the same I think, as the user wants to hide the panel shadows only when the window is maximized, when the window is not maximized and it is partially touching the panel edge showing the panel shadow creates a good effect.

**The above proposal of course creates the following:**
![default](https://user-images.githubusercontent.com/2216474/34328924-cf0f126e-e8f6-11e7-82c4-c87d0c39d6aa.png)

**instead of :**
![default](https://user-images.githubusercontent.com/2216474/34328928-f9822202-e8f6-11e7-9b52-5f39070c4ec4.png)

and personally I dont know which of these two is better...

demonstration of first case:

![](https://thumbs.gfycat.com/ElegantAnnualFiddlercrab-size_restricted.gif)

**EDIT:**

**Proposal 3** is the following:

Windows that should trigger  a solid background under Dynamic Background feature:

- any active window that is touching the panel edge (that includes krunner)
- any inactive window that is snapped and touches the panel edge (concerning its geometry: quarter-snapped or half-snapped )
- maximized windows
- ~~special case the yakuake app that should be taken into account either active or inactive~~
- **EDIT: when an inactive window but keepAbove is touching the panel edge (this catches also the yakuake case)**
- panel popups are already supported in the interaction...

**Comment by stephansama** [comment]
I think the first option is the best it looks nice

**Comment by JenaPlinsky** [comment]
for me also the 1

**Comment by psifidotos** [comment]
only thing with the first option is that in order to have a semi-transparent panel **there must not be any window touching its panel edge**!! And I dont know if the users using that option would like this...

**Comment by psifidotos** [comment]
**Proposal 3** is the following:

Windows that should trigger  a solid background under Dynamic Background feature:

- any active window that is touching the panel edge (that includes krunner)
- any inactive window that is snapped and touches the panel edge (concerning its geometry: quarter-snapped or half-snapped )
- maximized windows
- special case the yakuake app that should be taken into account either active or inactive
- panel popups are already supported in the interaction...

**Comment by stephansama** [comment]
I like the update. Proposal 3 seems like a great compromise

**Comment by psifidotos** [comment]
I really like the **Proposal 3** and it is also ready in my system :) , I will uploaded it in the new new year... :) because I need to update also the strings and tooltips in Tweaks page concerning Dynamic Background...

**Comment by Petross404** [comment]
> but I dont want to provide extreme configurability about this...

@psifidotos Both you and audoban are doing a great job. Latte Dock is steadily maturing (if it's not already). 

Why not unleash the full power and potential of it? Do what you do best with Latte and let the user decide and customize every in and out of it. For example for a future version you could consider providing a seperate clean and tidy qt window, with simple and expert mode where the user can configure latte.

Sorry if I am off-topic.

**Comment by stephansama** [comment]
@petross404 I agree. The more customizability the better. In my opinion.

**Comment by psifidotos** [comment]
@Petross404 unfortunately for some months now  audoban is not active to the project.

Concercning the.specific feature I am already fond of proposal 3.

For more customizability I think Latte is already providing a very good balance of simplicity and customizability... any new feature must respect that balance...

For a new more complete advanced configuration window I dont like the idea.

**Comment by koma111** [comment]
@Petross404  The easy/advanced idea is great! I think every bit of KDE should work like that. This approach would take their new motto "Simple by default, powerful when needed" beyond perfection.

However, not in a separate qt window. It would have to be completely rewritten, and would produce extremely strange behaviour. For example, what if the config window loses focus and another window is raised? In that case, what happens with the dock which is in edit mode? And could the config window be snapped, maximized, dragged around (maybe even out of the dock's screen!)? A popup is easier. Also because if it was a window, one would have to close it with the close button, but if it is a popup, the user can click anywhere else to quit configuration.

@psifidotos I like the easy/advanced idea very much. It wouldn't be that bad. It only takes some more sliders and checkboxes and one toggle (which is already present) which toggles the advanced options. (or hides the easy ones and shows the advanced ones instead).

If not an entire new level of configuration, just one toggle, please! Please let us disable the dynamic background for popups! I understand the reason of it, but it looks strange to me. For example, I have a vertical dock with a Simple Menu in it. Simple Menu is an app launcher plasmoid, much like a small version of Application Dashboard. It is placed some 20px away from the dock. When no window is shown, this is odd.

**Comment by psifidotos** [comment]
> Please let us disable the dynamic background for popups! 

I dont understand why you would need this... open a new feature request with screenshots and explanation why this is needed...
