### ISSUE TITLE
[Plasma 5.12] - a task shows an empty space instead of its icon

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/Latte-Dock#846]

**Comment by psifidotos** [comment]
@marhkb when such cases occurs:

1. if you enable the parabolic effect is it fixed?
2. if you click the icon does the window appears correctly?

**Comment by marhkb** [comment]
1. Unfortunately not
2. Yes either the the application starts if it's not  already running or it's focused

I made an easy setup where I can reliable reproduce it:

1. have two activities
2. set application filter to show only windows of current activity and leave both other filters unchecked
3. the first two starters are set to be shown on all activities
4. the third starter on each activity is special
5. Initially no application is running at all
6. On the first activity click on the first of the 3 starters and wait for program to start
7. switch to the second activity ...
8. ... and switch back to first
9. now the third starter is empty
 9.1. if you click the empty starter the program behind it opens and the correct image is shown again
 9.2. if you close the program of the first starter then the correct image is shown again 

I recorded it.
In the video I first switch activity in order to NOT have the recording tool in running in application area initially, because the issue doesn't appear then.
One can see that stock icons_only_taskmanager isn't affected by this issue (running in top dock)

[reproduce.flv.zip](https://github.com/psifidotos/Latte-Dock/files/1679377/reproduce.flv.zip)

**Comment by psifidotos** [comment]
I still cant reproduce by following exactly the above steps...

Can you export and send me that layout to check if it is a specific setting creating this?

**Comment by psifidotos** [comment]
and one more thing are you using latte 0.7.3 or the master version ?

**Comment by marhkb** [comment]
I think I found the culprit.
Do you see that separator before the trash?
If I remove it, then the issue is magically blown away.
Weird

**Comment by psifidotos** [comment]
> If I remove it, then the issue is magically blown away.

I will need your layout to try to reproduce with the steps you said...

**Comment by marhkb** [comment]
[activity_issue.layout.latte.zip](https://github.com/psifidotos/Latte-Dock/files/1679553/activity_issue.layout.latte.zip)

**Comment by marhkb** [comment]
> and one more thing are you using latte 0.7.3 or the master version ?
on master

**Comment by psifidotos** [comment]
unfortunately I  couldnt reproduce... in your file there is only thing suspicious... some of the launchers are using the old plasma style... and more specific the dolphin one... try on unpin it and repin it in order to check that this wasnt the issue... Also, the layout you sent me isnt the same with the videos... in videos the bottom panel is using justify alignment I think...

**Comment by marhkb** [comment]
I just created this layout from scratch in order to find the issue. 
So I kept it as simple as possible and with plasma standard application so that it can be used by you.
With this layout the bug is 100% reproducible on my side.
I even tried this with a new user account.
Weird that old plasma style launchers are used, because starters where created just a few minutes ago.
I just exported the the layout.

The layout seems to be irrelevant as I figured out as long as 
1. the first and second starters are global
2. the third starter is special
3. And most important after the third starter there is this audoban separator

A pity it can not be reproduced. I'll try this at work tomorrow. The computer has an AMD Card.
Maybe its driver related?!

**Comment by psifidotos** [comment]
no idea yet... :) it is very weird...

**Comment by psifidotos** [comment]
changing staff in the code and moving around things, this occured to me but it happened because of an error! what is your `latte-dock -d` output?

**Comment by marhkb** [comment]
[latte.log](https://github.com/psifidotos/Latte-Dock/files/1693070/latte.log)

**Comment by psifidotos** [comment]
unfortunately nothing special in there...

**Comment by marhkb** [comment]
I could not try it on another machine. Had much work. Next week I try to test at work.

**Comment by psifidotos** [comment]
totally a separators issue... It appeared when I upgraded to Plasma 5.12...

@marhkb I made a commit in case that was it... can you please also check if we had any improvement?

**Comment by psifidotos** [comment]
> Unfortunately I can still reproduce this with the steps above at least at home :-(

I fall into it accidentaly after upgrading to plasma 5.12 but now with latest commits I cant reproduce :(

**Comment by marhkb** [comment]
I just tested at work and I am able to reproduce it there, too.
Everything is up to date (plasma, frameworks, and latte from master).
The computer at work has a radeon card.

Maybe it is Arch Linux specific?

**Comment by psifidotos** [comment]
Can you please send me again the exact layout you are using without changing any of its settings?

**Comment by marhkb** [comment]
In my standard layout I already removed the separator.
But I keep a Test layout for testing purposes for that issue.
Here it is:

[Test.layout.latte.txt](https://github.com/psifidotos/Latte-Dock/files/1708927/Test.layout.latte.txt)

**Comment by psifidotos** [comment]
@marhkb please test again with latest commit...

**Comment by marhkb** [comment]
Just built and I can still reproduce. :(
I know that you are a keen developer and I don't want to force you to put to much effort in this.
Because nobody else seems to be bothered by this issue and I can happily live without that separator. :-)

But if you want this to be fixed I would offer you to join to some sort of screen sharing/audio video call with me. Maybe we could debug it this way.

**Comment by psifidotos** [comment]
> But if you really want this to be fixed I would offer you to join to some sort of screen sharing/audio video call with me. Maybe we could debug it this way.

we could make a text chat and you could install runtime a specific special branch in order to tell me the output

**Comment by psifidotos** [comment]
when do you think this could be feasible?

**Comment by marhkb** [comment]
I have time now. I'm currently preparing some things, so it should be feasible in a few minutes. 
Just need to know which program to chat.
Just tell me when you have time

**Comment by psifidotos** [comment]
> Just need to know which program to chat. Just tell me when you have time

I am online at irc,  irc.freenode.net, channel #latte

**Comment by marhkb** [comment]
ok I will be there in a few minutes
