### ISSUE TITLE
Improve Parabolic Effect

### ISSUE THREAD

**Issue by andreyorst** [psifidotos/Latte-Dock#852]
Hello. I've discovered what particulary makes animation in Latte dock look not as good as it is done in plank or OSX dock. See video below:
[![Latte vs Plank on youtube](http://img.youtube.com/vi/eLv_4EPZtEA/0.jpg)](https://www.youtube.com/watch?v=eLv_4EPZtEA "Latte vs Plank on youtube")

In case you don't have access to youtube [latte vs plank.zip](https://github.com/psifidotos/Latte-Dock/files/1685879/latte.vs.plank.zip)

So when I move cursor to dock it starts "zoom animation". After that when animation is complete and I move pointer alongside Latte there is another animation, i'll call it "roll animation" with kinda different behavior, as now it detects position of cursor. So for example if i had a wacom tablet and jumped with cursor it would zom out and zoom in in other place immidiately. It would not do full zoom out, than do full zoom in animations. But not when im leaving dock, because zoom in animation is slow. And until it completes the zoom in animation the siderolling effect isn't applied. Compare plank with latte. Plank does it a lot smoothely because it dont wait until zoom in completes.

**Comment by psifidotos** [comment]
If it was that simple... :)

but on the other hand most of the heuristics are correct...
lets tell you what is valid:

1. Latte until the first complete zoom has occurred it animates its tasks with some slowness because if it didnt, it would happen instantly... When you were first hovering a task then instantly that task and its neighbours would become zoomed... Let's call this **state1**

2. After **state1** has ended then Latte paints its tasks with something I call internally  **directRender mode**. All tasks are painted instantly without any delay...

3. when the mouse leaves the dock then with some delay it returns to state1

The parabolic animation in Plank is probably implemented in other way and I cant analyze it any further about how it is doing it...

On the other hand what is more important for me is how the parabolic animation works in **directRender** mode, @andreyorst is that sufficient for you? because if it isnt I dont think any better can be done... Latte is using QML in order to paint its tasks and Plank I think is doing it directly... Plank is using around 25-35Mbyte memory in its normal usage with also minimum cpu usage and on the other hand Latte uses around 130-160Mbyte with much more cpu.... 

So, personally for me is as good as it can be for now... anyone wanting to dirt its hands and provide improvements I would be more than happy to support him and explain him the internals...

**Comment by andreyorst** [comment]
> On the other hand what is more important for me is how the parabolic animation works in directRender mode, @andreyorst is that sufficient for you?

The parabolic effect is done good enough, the only issue is with that zoom before it. That's the reason why I used word "_partly_" in issue name. 

The parabollic effect is eye-candy. I believe, that users who need maximum performance won't use such silly things, so it could be done with sootheness in mind first. 

As a possible solution I see is to increase zoom in atimation speed. Or to drop zoom in animation if cursor moved too fast (which i think is the way plank do it. Need to use slowmotion recording to figure that out).

**Comment by psifidotos** [comment]
> As a possible solution I see is to increase zoom in atimation speed. Or to drop zoom in animation if cursor moved too fast (which i think is the way plank do it. Need to use slowmotion recording to figure that out).

feel free to provide patches for review... or a qml prototype that provides that smoothness (i could take your prototype and adjust it to Latte)

**Comment by psifidotos** [comment]
@andreyorst are you able to use master version?

**Comment by psifidotos** [comment]
I added the following criteria:

```
    fix #852,go to directRenderMode faster
    
    --in order to go faster to directRenderMode in some
    cases, the following criteria was added. If the zoomScale
    of a task is greater than 1 and the mouse enters that task
    then directRendering is enabled.
```

I will wait the feedback around this, in case it can be improved more...

**Comment by andreyorst** [comment]
> are you able to use master version?

Just builded it. Well It works way better now. But some lags are now visible, maybe it's my videodriver, though.

Only one small change is needed, as I see that nothing else can be done with this implementation. Please try to increase zoom in animation speed (if it is possible ofcourse). Because now it has nothing with animation speed regulator in the settings:
![image](https://user-images.githubusercontent.com/19470159/35722171-484634f4-0806-11e8-9b88-76e06874937b.png)
Zoom in duration is the same for all settings. I think that current duration should be related with x2 setting, x1 should be faster, and (possibly) "None" should turn off zoom in animation at all. But you better experiment with this.

**Comment by psifidotos** [comment]
> But some lags are now visible, maybe it's my videodriver, 

probably the new mechanisms need adjustment...
show me in a video what you mean...

> Zoom in duration is the same for all settings

this isnt accurate, based on the implementation it isnt the same... it is already relevant to (x2) duration... x1 is slighter faster and x3 is slightly slower... it can be done faster for x2 and that should influence of course the x1 and x3

> "None" should turn off zoom in animation at all.

did you test this? it is already that way

**Comment by andreyorst** [comment]
> did you test this? it is already that way

I mainly ment disable only zoom in animation, but not disabling effect entirely, so parabolic effect will remain and will be controlled with the slider.

> show me in a video what you mean...

That's my compositor vsync issue for sure. All appearing and disappearing plasma elements, like sound indicator, lag this way. I've tested rightnow, so it's not latte issue.

> this isnt accurate, based on the implementation it isnt the same...

Well at least i didn't notice any difference. Overall speedup can make this a lot smoother. THere were some guidelines for designing right animation speed based on psycology research, I'll try to find it if you interested.

I will look through the code during weekend, so can you please provide a list of source files where i should look for parabolic effect implementation? I'm not so familiar with plasmoid developing (in fact i've tried once, and all i came with was a button on panel which showed a menu with only one button that should close this menu, but that didn't worked as well) but i'll try to compare docky's implementation with yours. Mayby i'll find some new way.

**Comment by psifidotos** [comment]
> I mainly ment disable only zoom in animation, but not disabling effect entirely, so parabolic effect will remain and will be controlled with the slider.

makes sense... even though many things will need to be adjusted for such case.... but it is feasible.


for the plasmoid case you can look at:
```
plasmoid/package/contents/ui/task/TaskWrapper.qml
plasmoid/package/contents/ui/task/TaskDelegate.qml
plasmoid/package/contents/ui/ParabolicManager.qml
```

it is a bit complex and sophisticated, but as general architecture it works like this: 
- each task when contains the mouse zooms in and sends to its two neighbours two signals about how much they must be zoomed in (ParabolicManager makes these calculations after it is called from the current task).

the zoom in animation speed can be found at TaskWrapper.qml, (line 119):

```
    Behavior on mScale {
        enabled: !root.globalDirectRender || inMimicParabolicAnimation
        NumberAnimation { duration: 3 * mainItemContainer.animationTime }
    }
```

by changing the duration value you can make faster or slower...

**How To Test:**

1. make your changes
2. install Latte again
3. close Latte
4. rerun Latte

**Comment by psifidotos** [comment]
@andreyorst you could test again... a lot of improvements for parabolic animation....

**Comment by JenaPlinsky** [comment]
Great job guys !!! 
the improvement seems to be consistent 
Great job guys !!! the improvement seems to be consistent here is a super slowmotion to better observe the details
here is a super slowmotion to better observe the details
![screencast_2018-02-04_190850_slowmotion](https://user-images.githubusercontent.com/24593950/35781451-9aa0d160-09ea-11e8-9e7d-00b6c7f61237.gif)
![screencast_2018-02-04_193322_slowmotion](https://user-images.githubusercontent.com/24593950/35781452-9c6e4aae-09ea-11e8-8a9a-5a95a9998283.gif)
![screencast_2018-02-04_192638_slowmotion](https://user-images.githubusercontent.com/24593950/35781454-9e9f6d76-09ea-11e8-9e99-c24e5cab017a.gif)

**Comment by psifidotos** [comment]
> Great job guys !!!

unfortunately I am the only developer for more than 4 months :)

**Comment by JenaPlinsky** [comment]
Great job guys !!! 
the improvement seems to be consistent 
Great job guys !!! the improvement seems to be consistent here is a super slowmotion to better observe the details
here is a super slowmotion to better observe the details
![screencast_2018-02-04_190850_slowmotion](https://user-images.githubusercontent.com/24593950/35781451-9aa0d160-09ea-11e8-9e7d-00b6c7f61237.gif)
![screencast_2018-02-04_193322_slowmotion](https://user-images.githubusercontent.com/24593950/35781452-9c6e4aae-09ea-11e8-8a9a-5a95a9998283.gif)
![screencast_2018-02-04_192638_slowmotion](https://user-images.githubusercontent.com/24593950/35781454-9e9f6d76-09ea-11e8-9e99-c24e5cab017a.gif)

**Comment by andreyorst** [comment]
Yes, It works way better now. I've managed to look through plank's implementation, and I've tried to implement it the same way, but no luck.

The parabolic effect now works flawlessly. But the zoom in animation still kinda slowish. It's because it isn't using directrender? Can you explain me why not to use direct rener for zooming in? You can still use the same way to render plank when it is not interacted with pointer movement, and turn direct render upon zooming in. Let me explain why this should be better (visually):
1. When dock isnt zoomed, the frame that rendered before the actual zoom starts, and the first frame of zooming in are almost the same. So you can seamlessly switch rendering mode here.
2. When you zoom icons and turn on directrender after it, then last frame of zoom in and first frame of directrendered parabolic effect may be very different because humans are not robots and pointer isn't rests still.

And for now I can easilly spot that zooming in has less frames per second then parabolic effect. In case you dont want to mess with zooming in with directrender then i can suggest you to increase zooming speed.
I've got best results with 0.5 or 1 modifiers:
```qml
    Behavior on mScale {
        enabled: !root.globalDirectRender || inMimicParabolicAnimation
        NumberAnimation { duration: 0.5 * mainItemContainer.animationTime }
        // NumberAnimation { duration: 1 * mainItemContainer.animationTime }
    }
```
But the lack of FPS while zoomin in is still noticable

**Comment by psifidotos** [comment]
Ok,.. Let me describe you the approach because it is clear that you havent understand the difference between zoom-in and directrender modes...

We have three tasks: [1] - [2] - [3] and the mouse isnt inside the dock. The user has chosen 80% zoom factor when hovered. This works like this....

The user enters its mouse in task [2]. That specific task indicates that and set its zoom to 80%, at the same time that specific task based on the mouse movement inside its boundaries calculates the zoom factors for its neighbours. If the mouse is in the task center then its neighbours should zoom at 40%, and for them it sends the appropriate signals. Its neighbours catch these signals they understand that it is for them and update their zoom to 40%.

The above example happens always and at all cases both for zoom-in and directrendering. 

Zoom-In **vs** DirectRendering

1. In Zoom-In mode, when a task must go from zoom 0% to 80% it is doing it in steps. e.g. 5%, 7%, 8% , 10%, 15%, 20% etc... this is provided by the Behavior code demonstrated previously.

2. In DirectRender mode when a task must go from zoom 0% to 80% it is doing it instantly. e.g 0% -> 80%

We need Zoom-In when the user enters the dock for the first time otherwise it would go from 0%->80% instantly, that doesnt show any painting at all. In one frame you ve got 0% and at the next frame 80%

To go from Zoom-In to DirectRender there are two cases based on the last commits:
a) the zoom-in ended (that is a task reached the maximum zoom e.g. 80%).
b) the user moved its mouse from the first entered task to its neighbors.


> When dock isnt zoomed, the frame that rendered before the actual zoom starts, and the first frame of zooming in are almost the same. So you can seamlessly switch rendering mode here.

yes I could but as described above that would break the painting totally

> When you zoom icons and turn on directrender after it, then last frame of zoom in and first frame of directrendered parabolic effect may be very different because humans are not robots and pointer isn't rests still.

yes that is correct, even though during  Zoom-In the mouse position is taken into account at all times. but because there is the Behavior it might be delayed a bit the correct position.

> And for now I can easilly spot that zooming in has less frames per second then parabolic effect. In case you dont want to mess with zooming in with directrender then i can suggest you to increase zooming speed. I've got best results with 0.5 or 1 modifiers:

not in my system... Even with 2.5 modifier and chosen Animations to x2 the animation loses a lot of frames, it is almost instantly.

So based on your arguments the only issue in the current approach is when going from Zoom-In to DirectRendering at the end of Zoom-In. That switch could create a small animation breakage because the last frame of Zoom-In and the first of DirectRendering could be slighthly different,

But do you have any other solution for this? Do you know any other way to handle Zoom-In  when the user first enters the dock?

An alternative could be to change from NumberAnimation to something that accelerates at the end or the opposite, this is how I improved the painting a bit for the blue paper sliding in when showing the Latte settings...

Currently we are using Easing.Linear for Zoom-In animation (http://doc.qt.io/qt-5/qml-qtquick-propertyanimation.html#easing.type-prop)

**Comment by andreyorst** [comment]
Understood. I'll think for a while about it.

**Comment by psifidotos** [comment]
> Understood. I'll think for a while about it.

I updated the zoom-in animation type... in my system it gives me more painting...

**Comment by andreyorst** [comment]
Omg. thats way better. Yet I modified TaskWrapper.qml to speed up zooming effect a little
```qml
Behavior on mScale {
    enabled: !root.globalDirectRender || inMimicParabolicAnimation
    NumberAnimation{
        duration: 3 * mainItemContainer.animationTime // less noticable lag on side mouse enter
        // duration: 2.5 * mainItemContainer.animationTime // faster, but lags on entering from the side
        easing.type: Easing.OutCubic
    }
}
```

But now there is another problem:
```
latte-dock --replace
KCrash: Attempting to start /usr/bin/latte-dock directly
KCrash: Application 'latte-dock' crashing...
KCrash: Attempting to start /usr/lib/drkonqi directly
Using /proc to determine executable path
Executable is: "/usr/bin/latte-dock"
Executable exists: true
Enabling drkonqi crash catching
Sending SIGSTOP to process
[1]  + 6572 suspended (signal)
```

Represents with any value in duration formula.

**Comment by psifidotos** [comment]
>  to speed up zooming effect a little

it may depends a bit to the graphics stack... I suppose wayland will show exactly what is happening with painting...

> When I click with right button latte crashes. Represents with any value in duration formula.

I can reproduce... it may be irrelevant with duration etc... if you try master version without changing anything it crashes for you ?

**Comment by psifidotos** [comment]
EDIT: I cant reproduce that crash... what is the crash report?

**Comment by andreyorst** [comment]
> if you try master version without changing anything it crashes for you?

Yes. Launched with `latte-dock --debug`. [Full log](https://github.com/psifidotos/Latte-Dock/files/1696350/latte_log.txt)

The crash part:
```
[fatal 21:42:34.801801] - KActivities: Database can not be opened in WAL mode. Check the SQLite version (required >3.7.0). And whether your filesystem supports shared memory
?libKF5ActivitiesStats.so.1?
KActivities::Stats::ResultSet::ResultSet
?libtaskmanagerplugin.so?
?libtaskmanagerplugin.so?
?libQt5Qml.so.5?
?libQt5Qml.so.5?
?libQt5Qml.so.5?
QV4::QObjectMethod::callInternal
KCrash: Attempting to start /usr/bin/latte-dock directly
KCrash: Application 'latte-dock' crashing...
KCrash: Attempting to start /usr/lib/drkonqi directly
[warning 21:42:35.9494] - QSocketNotifier: Invalid socket 8 and type 'Read', disabling...
[warning 21:42:35.9494] - QSocketNotifier: Invalid socket 19 and type 'Read', disabling...
[warning 21:42:35.941941] - QSocketNotifier: Invalid socket 10 and type 'Read', disabling...
Using /proc to determine executable path
Executable is: "/usr/bin/latte-dock"
Executable exists: true
Enabling drkonqi crash catching
"An instance is already running!, use --replace to restart Latte"
Sending SIGSTOP to process
[2]  + 7858 suspended (signal)
```

**Comment by psifidotos** [comment]
what plasma version are you using... this is a totally different crash and irrelevant with this issue... 
 These are very suspicious... it is like you plasma Activities infrastructure may be broken... If you use plasma panel and plasma taskmanager in it, it doesnt crash?

**Comment by andreyorst** [comment]
KDE Plasma 5.11.5
KDE Frameworks: 5.42.0
Qt: 5.10.0
> it is like you plasma Activities infrastructure may be broken

What do you mean by _broken_

**Comment by andreyorst** [comment]
hm. Tried on my work PC. An there is no problem.

**Comment by psifidotos** [comment]
> What do you mean by broken

inconsistent, not working properly

>  (yet I'll modify zoomin and zoomout to be faster in my particular setup)

yeah... I will checkout at wayland at some point to confirm also the timing...

**Comment by psifidotos** [comment]
@andreyorst concerning the shifting that was noticed on first hovering I think that latest commits must have fixed it...

**Comment by andreyorst** [comment]
Sure! Works great!
