### ISSUE TITLE
Latte shows panel shadow for a few milliseconds when opening menu from "Active Window Control"

### ISSUE THREAD

**Issue by marhkb** [psifidotos/Latte-Dock#862]
Haven't noticed this before. Maybe the issue appeared after updating to the latest "Active Window Control" git version because of getting an global app menu at all in plasma 5.12.0
Now when opening a menu item, the panel shadow is shown for a few milliseconds what somehow looks glitchy.
Before the menu opens, the shadow is gone.
I think the shadow either should not be drawn at all or should stay as long the the menu is opened.
I am on latte master branch.

**Comment by psifidotos** [comment]
yep... the new AWC activates itself on every menu showing... it must be blacklisted from some heuristics

**Comment by Tichy** [comment]
I have the same behaviour with plasma's own global menu, when setting latte to show the background only for maximized windows.

I think that the best behaviour in this case, would be to show the background when opening a menu, like it happens when you click on an applet (eg. media control, volume, clock).

**Comment by psifidotos** [comment]
> I think that the best behaviour in this case, would be to show the background when opening a menu, like it happens when you click on an applet (eg. media control, volume, clock).

I dont agree because these menus dont follow the plasma theme like the applets but the widgets theme...

The fast appearing/disappearing can be fixed by blacklisting the plasmoid like the AWC

**Comment by psifidotos** [comment]
> I think that the best behaviour in this case, would be to show the background when opening a menu, like it happens when you click on an applet (eg. media control, volume, clock).

I reread your comment... what you propose is to have solid background when the menus are showing... these is an upstream request for these plasmoids... you can ask by their developers to set as active their plasmoids when they are showing their menus. Latte will trigger automatically the proposed behavior afterwards.

**Comment by Tichy** [comment]
Thanks. I did submit a request https://bugs.kde.org/show_bug.cgi?id=390271

What do I need to do to blacklist the plasmoid? And what happens if I do this?

**Comment by psifidotos** [comment]
> What do I need to do to blacklist the plasmoid? And what happens if I do this?

the blacklisting is done in the Latte code for specific plasmoids that do not behave as they should with Latte functionality, so this isnt on the user side...

**Comment by davidedmundson** [comment]
Whilst us setting this applet to active is an option, you might need to do another fix anyway.

In panelview for autohide, I got so frustrated with all the code we had to do with managing applets and settings not being active when they had windows or config menus or whatever open I did this fix:
2d8b4e1dec26c5976dd75c238c3ae8a4700b8dd9 in p-w.

If your shadow switching worked on the same principle, it might be a solution.

**Comment by psifidotos** [comment]
> If your shadow switching worked on the same principle, it might be a solution.

it makes sense but I would need to blacklist the config windows from applets, the context menu of the view etc... but makes sense... I will play around with it...

**Comment by psifidotos** [comment]
>  it might be a solution.

thanks David

**Comment by davidedmundson** [comment]
My point was that I didn't have to write special code for config windows or context menus; as this generic code took care of all of it doing what we wanted.

If for Latte, you do have to write custom code for those then it's not worth doing.

**Comment by psifidotos** [comment]
> If for Latte, you do have to write custom code for those then it's not worth doing.

unfortunately that is the case... because the example 2 case I dont think it work out well visually for applets config windows and contextmenus.

example 1 (clock that it isnt active, semi-transparent panel  with no panel shadows)

![default](https://user-images.githubusercontent.com/2216474/36173541-16947f64-1112-11e8-81dd-5b2bb8f71fbd.png)


example 2 (the same clock becomes active, and the panel automatically becomes solid and draws its shadows)

![default](https://user-images.githubusercontent.com/2216474/36173613-44959074-1112-11e8-8669-e3430773edb0.png)

**Comment by psifidotos** [comment]
@davidedmundson I think that I must create a different implementation for this... Currently in order for Latte to check is an applet has a popup it uses the following code: 

```
    readonly property bool hasExpandedApplet: plasmoid.applets.some(function (item) {
        return (item.status >= PlasmaCore.Types.NeedsAttentionStatus && item.pluginName !== root.plasmoidName
                && item.status !== PlasmaCore.Types.HiddenStatus);
    })
```

hasExpanded in the sense of showing a popup... I played also around with the expanded value of the applet but didnt help because an applet can be expanded inside a panel without having any popup. I suppose your solution is the only one and blacklist the windows that are irrevelant...

Do you agree? is there any easier approach?

**Comment by psifidotos** [comment]
@davidedmundson 

I created this for AWC: https://phabricator.kde.org/D10516
and for plasma I think I could do the same for #setMenuAvailable: https://github.com/KDE/plasma-workspace/blob/master/applets/appmenu/plugin/appmenumodel.cpp#L94
