### ISSUE TITLE
Run-time dependencies for non-Plasma DE's?

### ISSUE THREAD

**Issue by CliffordD** [psifidotos/Latte-Dock#866]
I am led to believe that latte-dock should run on non-Plasma desktop environments.  What are the run-time dependencies it needs for it to run?

Currently in GNOME is runs, but displays nothing.  Displaying the message "requested containment plugin can not be located or loaded" when started from terminal

**Comment by psifidotos** [comment]
> I am led to believe that latte-dock should run on non-Plasma desktop environments. What are the run-time dependencies it needs for it to run?
> Currently in GNOME is runs, but displays nothing. Displaying the message "requested containment plugin can not be located or loaded" when started from terminal

It can run in X11 environments but needs also some plasma desktop packages because the plasma shell is the base upon which Latte shell is built...

if you have installed `plasma-framework`, then afterwards you can try `plasma-workspace` and if this isnt the one then `plasma-desktop` it should do it...

it can even load plasmoids in foreign environments but it needs first to be added through plasma desktop because the Latte Add Widgets is just a call for the plasma one window...
