### ISSUE TITLE
Crash after KDE Plasma update

### ISSUE THREAD

**Issue by gregoireTN** [psifidotos/Latte-Dock#870]
Hi ! 

Latte Dock crash every time after each upgrade of KDE Plasma, like https://github.com/psifidotos/Latte-Dock/issues/788

The solution with the clearing qmlcache (in ~/.cache/lattedock/qmlcache) works.

Perhaps we can add a test on the startup of Latte-Dock : test the version of KDE Plasma, if the version is updated, the cache is cleared. 

(Excuse-me for my bad english : it's not my natural language)

**Comment by psifidotos** [comment]
This would be workaround for a qt issue, and also it is something that Latte shouldnt be responsible to do, so I cant accept such workaround because cache is an area that i dont want to touch...

Thing is that this occurs only with specific distros so i dont know who really is responsible... i am confident that Latte isnt the quily here for cache issues....

**Comment by tbole** [comment]
Have the same problem after an upgrade. Strange thing is, this bug occurs only for Latte, not one single other KDE / Qt based tool is affected.
