### ISSUE TITLE
Keyboard volume control doesn't work when there is no (non-latte) panel

### ISSUE THREAD

**Issue by jeep70** [psifidotos/Latte-Dock#875]
While trying out Latte-Dock as a replacement to KDE's panels, I noticed that if I don't have a regular KDE panel with a system tray/volume widget on it, I couldn't control my volume using my keyboard's volume wheel.

**Comment by jeep70** [comment]
Nevermind, it seems like it's not Latte's fault. The volume just stops working whenever it wants to, and making a new volume widget fixes it for whatever reason.

**Comment by jeep70** [comment]
You know what, I'm not crazy. It's definitely something weird with the lack of a KDE panel

**Comment by jeep70** [comment]
Okay, I think what I was noticing was when I created a KDE panel with a volume widget, it "took over" control of the keyboard volume. When I re-create a volume widget with latte or switch layouts, it starts working again.

**Comment by jeep70** [comment]
And it's happening at random again. Probably something wrong with my installation, forget it.

**Comment by psifidotos** [comment]
Volume control is provided by the systray...
if the systray is in a plasma panel it should be provided by it and if the systray is a latte panel from this one... systrays cant be used in combination meaning that both latte and plasma can have one because this creates crashes because of the systrays internals for which I havent investigated further... Having the systrays only in plasma panel or only in latte panels should fix any issues in that regard... If the issues remain then it must be something with the systray or the specific machine...
