### ISSUE TITLE
Double icon of app when running it

### ISSUE THREAD

**Issue by nivaca** [psifidotos/Latte-Dock#878]
This only happens with Emacs, as far as I have been able to determine. 
When Emacs is not running, there is only one icon on the dock. When I run it (from the dock or elsewhere) I get two icons. See attached images.

I am running version 0.7.3-1 on Arch Linux (kernel 4.15.3-2-ARCH)  with KDE Plasma (version 5.12.2).

Before running Emacs:
![screenshot_20180222_105302](https://user-images.githubusercontent.com/2309005/36548555-9aa25d6e-17be-11e8-97f3-369b29bef78a.png)

Running Emacs:
![screenshot_20180222_104732](https://user-images.githubusercontent.com/2309005/36548552-9a6882ba-17be-11e8-89b2-c1ecd53c21d9.png)

**Comment by psifidotos** [comment]
you will have the same issue but either way to fix this you need to fix the desktop file for your emacs...

1. open an emacs window and exexute `xprop` for it
2. Locate in the output : `WM_CLASS(STRING)`
3. find your desktop file and add because probably there isnt already in it a value for `StartupWMClass` that equals the class string you located at (2)

e.g.

`StartupWMClass=Thunderbird`

**Comment by nivaca** [comment]
Thanks. That did the trick.
