### ISSUE TITLE
[Feature Request] Launcher only dock

### ISSUE THREAD

**Issue by beojan** [psifidotos/Latte-Dock#901]
The ability to show only pinned items (and to add pinned items without opening them) to create a launcher only dock.

**Comment by psifidotos** [comment]
I think I found a way to support this.
As I am thinking it the plasmoid shoul NOT show windows that dont have launchers present.

What is happening concerning the active indicator? is it shown as usual?

**Comment by beojan** [comment]
That's pretty much exactly what I was looking for.

> What is happening concerning the active indicator? is it shown as usual?

I'm of the school of thought that if you don't have a strong opinion, you should just make it configurable. In this case, I would simply allow switching the active indicator off (in all cases).

**Comment by psifidotos** [comment]
@beojan can you use master version?

> I would simply allow switching the active indicator off (in all cases).

this can be achieved for Active Indicator at Appearance page, if the user chooses None then the active indicator could become hidden. In such case what happens when the user clicks on it?

e.g. There is no active indicator for a dolphin launcher but there is a dolphin window present in the desktop. By clickin on it do we create a new instance or we activate/minimize etc the window?

**Comment by beojan** [comment]
In most cases, I think activating the existing instance makes the most sense. Presumably, the option would be phrased along the lines of "Show favourites only" with a list of favourites to configure (else it becomes cumbersome to choose the favourites, since you would have to turn the feature off, open the applications you want and pin them, then turn the feature on again), so this is what a user would expect. 

Ideally it would be configurable per launcher, but I don't think that's possible.

**Comment by beojan** [comment]
> can you test master version?

I am. I don't see any such filter.

**Comment by psifidotos** [comment]
not a simple thing to implement... basic functionality is in there now, I suppose it will have some issues but it is a start...


![default](https://user-images.githubusercontent.com/2216474/38433101-4e0113de-39d2-11e8-998a-1c0eb0ca68bc.png)

**Comment by Schyken** [comment]
I'm late to the party, but yeah, this is absolutely the functionality I was looking for. (So far, people have thought I meant only showing launchers :3) Whenever it's open for testing, I'd be happy to do so and provide the resulting feedback here.

As for issues with this, what seems to be some of the challenges with it?

**Comment by psifidotos** [comment]
> Whenever it's open for testing, I'd be happy to do so and provide the resulting feedback here.

it is already merged in master version... :)

> As for issues with this, what seems to be some of the challenges with it?

The difficulties and challenges are from plasma libtaskmanager. By design Latte uses the default plasma libtaskmanager functionality. Of course that helps a lot because whatever plasma improves, Latte will gain also but on the other hand the plasma limitations are creating difficulties to implement different things or different use cases.

Plasma libtaskmanager by design creates plenty of additions/removals per task.
Launcher<->Startup<->Window . To go from one record to another libtaskmanager creates a delete and an addition afterwards. But for Latte that has so many animations this was a puzzle have to achieve not be noticed by the user and how all this could be orchestrated... Finally with v0.8 I think this has been orchestrated pretty well. So the user even though he clicks just a launcher it doesnt understand what magic a logic is hidden behind until the window is shown in Latte.

For that specific feature I dont think that plasma libtaskmanager was going to be able to accept such feature. So based on the previous orchestration something should be done so that irrelevant windows to be not shown and to be hidden by the user... You get the point...  A lot of orchestration under the ground and in a way that this new ability doesnt break the main use case.

All this has been landed and you can test it at master version.
