### ISSUE TITLE
Latte freezes when adding icon only task manager

### ISSUE THREAD

**Issue by DoubleIntegral** [psifidotos/Latte-Dock#910]
Latte 11cccbf 
Layout: https://hastebin.com/edocudebip.md

Now this is a strange one.  I remove icon only launcher, change position, disable "Improve contents visibility" option. Now whenever I try to add icon only launcher latte consistently freezes. 

Steps to reproduce are kind of hard to explain since I was fiddling with widgets a lot but in general what happened:
1. I had Extended layout selected with "Improve contents visibility" enabled and icon only task manager in panel.
2. I disable "Improve contents visibility" option.
3. I remove icon only task manager from panel, move it to bottom of the screen, rearrange widgets
4. I select "Add Widgets" from context menu of latte panel. 
5. I select "Icon only task manager" from widget picker and drop it on Latte panel
6. Latte freezes consistently using 25% CPU

I think I borked my config somehow.

**Comment by psifidotos** [comment]
you havent...
I havent tracked that down yet...

please try the following:

1. open panel settings for the panel that you want to add the applet
2. click the sticker button at the top-right corner of the settings in order to not close when loses focus
3. try to add again the icon-only taskmanager but this time be sure that the Latte Dock/Panel settings are shown.

**Comment by DoubleIntegral** [comment]
Works. 
I seem to be on a lucky streak today with finding bugs :D

**Comment by psifidotos** [comment]
> I seem to be on a lucky streak today with finding bugs :D

no worries... ;)

it had happened to me also but the thing is that I dont understand yet where is the issue...
