### ISSUE TITLE
Widgets go out of bounds when adding them to a panel with widgets that have dynamic fill width

### ISSUE THREAD

**Issue by DoubleIntegral** [psifidotos/Latte-Dock#913]
Latte 11cccbf
Layout: Extended

Steps to reproduce:
1. Select Extended layout
2. Select "Add Widgets" from context menu.
3. Add widget that by default stretches to take free space (Task manager or icon task manager for example).
4. Close all the menus and select "Add Widgets" again.
5. Start adding more widgets to see panel overflow.

Screenshot: https://imgur.com/R3y7v1P

**Comment by psifidotos** [comment]
you mean in editing mode (when showing the Dock/Panel settings that is)...

yeah, it is a little strange because the calculations for fillWidths/Heights have been disabled for editing mode...

I will check it out if it is possible to reenable them without breaking something and not adding extreme cpu usage

**Comment by DoubleIntegral** [comment]
Yeah it does snap back to normal after you exit editing mode
